@extends('layouts.app')
@section('title','Executive Dashboard')
@section('content')
<div class="d-flex justify-content-between align-items-start mb-4"><div><h1 class="h3 page-title mb-1">Business overview</h1><p class="text-muted mb-0">Live financial, sales, inventory and master-data indicators.</p></div><span class="badge badge-soft px-3 py-2"><i class="bi bi-database-check me-1"></i> Database connected</span></div>
<div class="row g-4">@foreach($metrics as $label=>$metric)<div class="col-sm-6 col-xl-3">@if(isset($metric['route']))<a href="{{ $metric['route'] }}" class="text-decoration-none text-dark">@endif<div class="card h-100"><div class="card-body p-4 d-flex justify-content-between"><div><div class="text-muted small mb-2">{{ $label }}</div><div class="h4 fw-bold mb-0">{{ ($metric['money']??false)?'Rs. '.number_format($metric['value'],2):number_format($metric['value']) }}</div></div><div class="metric-icon"><i class="bi bi-{{ $metric['icon'] }}"></i></div></div></div>@if(isset($metric['route']))</a>@endif</div>@endforeach</div>

<div class="row g-4 mt-1">
    <div class="col-xl-8"><div class="card h-100"><div class="card-body p-4"><div class="d-flex justify-content-between"><div><h2 class="h5 fw-bold mb-1">Sales and gross profit</h2><p class="small text-muted">Last seven days</p></div><a href="{{ route('sales.index') }}" class="small">View sales</a></div><div style="height:310px"><canvas id="salesTrendChart"></canvas></div></div></div></div>
    <div class="col-xl-4"><div class="card h-100"><div class="card-body p-4"><div class="d-flex justify-content-between"><div><h2 class="h5 fw-bold mb-1">Outstanding position</h2><p class="small text-muted">Receivables versus payables</p></div></div><div style="height:250px"><canvas id="outstandingChart"></canvas></div><div class="row text-center mt-3"><div class="col"><small class="text-muted">Receivable</small><div class="fw-bold text-primary">Rs. {{ number_format($receivable,2) }}</div></div><div class="col"><small class="text-muted">Payable</small><div class="fw-bold text-danger">Rs. {{ number_format($payable,2) }}</div></div></div></div></div></div>
    <div class="col-xl-6"><div class="card h-100"><div class="card-body p-4"><div class="d-flex justify-content-between"><div><h2 class="h5 fw-bold mb-1">Cash and credit sales</h2><p class="small text-muted">All posted sales</p></div></div><div style="height:260px"><canvas id="saleMixChart"></canvas></div></div></div></div>
    <div class="col-xl-6"><div class="card h-100"><div class="card-body p-4"><h2 class="h5 fw-bold">Financial shortcuts</h2><p class="text-muted">Open the underlying records and reports directly.</p><div class="row g-3">@foreach([[route('accounting.accounts'),'diagram-3','Chart of Accounts','View every ledger account'],[route('accounting.trial-balance'),'list-columns-reverse','Trial Balance','Debit and credit balances'],[route('statements.index'),'file-earmark-bar-graph','Financial Statements','P&L, balance sheet and cash flow'],[route('accounting.journals'),'journal-bookmark','Accounting Journals','Posted double-entry transactions']] as [$url,$icon,$title,$text])<div class="col-md-6"><a href="{{ $url }}" class="border rounded-3 p-3 d-flex gap-3 text-decoration-none text-dark h-100"><div class="metric-icon"><i class="bi bi-{{ $icon }}"></i></div><div><div class="fw-semibold">{{ $title }}</div><small class="text-muted">{{ $text }}</small></div></a></div>@endforeach</div></div></div></div>
</div>

<div class="card mt-4"><div class="card-body p-4"><div class="d-flex justify-content-between align-items-center"><h2 class="h5 fw-bold mb-0">Development status</h2><strong>{{ $development['percent'] }}%</strong></div><p class="text-muted my-3">Core master data, purchasing, inventory, POS, receivables, accounting, payables and expenses are active. {{ $development['label'] }}.</p><div class="progress" style="height:10px"><div class="progress-bar" style="width:{{ $development['percent'] }}%"></div></div></div></div>
@endsection
@push('scripts')
<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.4/dist/chart.umd.min.js"></script>
<script>
const moneyTick = value => 'Rs. ' + Number(value).toLocaleString();
new Chart(document.getElementById('salesTrendChart'), {type:'line',data:{labels:@json($trend['labels']),datasets:[{label:'Sales',data:@json($trend['sales']),borderColor:'#2563eb',backgroundColor:'rgba(37,99,235,.12)',fill:true,tension:.35},{label:'Gross profit',data:@json($trend['profit']),borderColor:'#16a34a',backgroundColor:'rgba(22,163,74,.08)',tension:.35}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{position:'bottom'}},scales:{y:{ticks:{callback:moneyTick}}}}});
new Chart(document.getElementById('outstandingChart'), {type:'doughnut',data:{labels:['Customer receivables','Supplier payables'],datasets:[{data:[@json($receivable),@json($payable)],backgroundColor:['#2563eb','#ef4444'],borderWidth:0}]},options:{responsive:true,maintainAspectRatio:false,cutout:'68%',plugins:{legend:{position:'bottom'}}}});
new Chart(document.getElementById('saleMixChart'), {type:'bar',data:{labels:['Cash sales','Credit sales'],datasets:[{label:'Posted sales',data:[@json($saleMix['cash']),@json($saleMix['credit'])],backgroundColor:['#16a34a','#f59e0b'],borderRadius:8}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{y:{beginAtZero:true,ticks:{callback:moneyTick}}}}});
</script>
@endpush
