<?php

namespace App\Services;

use Illuminate\Support\Facades\DB;
use PhpOffice\PhpSpreadsheet\Cell\DataType;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Style\{Alignment,Border,Fill};
use PhpOffice\PhpSpreadsheet\Worksheet\PageSetup;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use RuntimeException;

class ReceivableXlsxExportService
{
    private const NAVY = '17396B';
    private const LIGHT_BLUE = 'EAF1FA';
    private const PALE = 'F2F6FB';
    private const GREEN = '17894C';
    private const RED = 'D92D3A';
    private const BORDER = 'DDE5EE';
    private const MONEY = '"Rs. "#,##0.00;[Red]-"Rs. "#,##0.00';

    public function create(array $report, int $companyId, string $generatedBy): string
    {
        $company = DB::table('companies')->where('id', $companyId)->first();
        $book = new Spreadsheet();
        $book->getProperties()->setCreator('Supun Group ERP')->setTitle('Customer Receivables Report')->setSubject('Customer balances and posted receipts');

        $summary = $book->getActiveSheet();
        $summary->setTitle('Summary');
        $this->buildSummary($summary, $report, $company, $generatedBy);
        $this->buildCustomers($book->createSheet(), $report);
        $this->buildReceipts($book->createSheet(), $report);
        $book->setActiveSheetIndex(0);

        $base = tempnam(storage_path('app'), 'receivables-');
        if ($base === false) throw new RuntimeException('Could not create the Excel report file.');
        $path = $base.'.xlsx';
        @unlink($base);
        (new Xlsx($book))->save($path);
        $book->disconnectWorksheets();
        return $path;
    }

    private function buildSummary($sheet, array $report, object $company, string $generatedBy): void
    {
        $scope = $report['selectedCustomer'] ? 'Customer: '.$report['selectedCustomer']->name.' ('.$report['selectedCustomer']->code.')' : 'All registered customers';
        $sheet->mergeCells('A1:F1')->setCellValue('A1', 'SUPUN GROUP ERP');
        $sheet->mergeCells('A2:F2')->setCellValue('A2', ($company->name ?? 'Supun Group').' - Customer Receivables Report');
        $sheet->mergeCells('A3:F3')->setCellValue('A3', $scope);
        foreach (['A5:B5'=>'TOTAL CREDIT SALES','C5:D5'=>'TOTAL PAID BY CUSTOMERS','E5:F5'=>'CURRENT RECEIVABLE'] as $range=>$label) {$sheet->mergeCells($range);$sheet->setCellValue(explode(':',$range)[0],$label);}
        foreach (['A6:B6'=>$report['totals']['invoiced'],'C6:D6'=>$report['totals']['received'],'E6:F6'=>$report['totals']['current_receivable']] as $range=>$value) {$sheet->mergeCells($range);$sheet->setCellValue(explode(':',$range)[0],$value);}
        $sheet->mergeCells('A8:F8')->setCellValue('A8','REPORT INFORMATION');
        foreach ([9=>['Generated at',now()->format('d M Y, H:i')],10=>['Generated by',$generatedBy],11=>['Customer accounts',$report['customers']->count()],12=>['Posted receipts',$report['receipts']->count()]] as $row=>$values) {$sheet->setCellValue('A'.$row,$values[0]);$sheet->mergeCells('B'.$row.':F'.$row)->setCellValue('B'.$row,$values[1]);}
        $sheet->mergeCells('A14:F14')->setCellValue('A14','NOTES');
        $sheet->mergeCells('A15:F15')->setCellValue('A15','This report includes posted credit invoices and posted customer receipts for the selected scope.');
        $sheet->mergeCells('A16:F16')->setCellValue('A16','Amounts are in Sri Lankan Rupees (LKR). Supporting details are available in the other worksheets.');

        $sheet->getStyle('A1:F1')->applyFromArray($this->titleStyle(20));
        $sheet->getStyle('A2:F2')->applyFromArray(['font'=>['bold'=>true,'size'=>13,'color'=>['rgb'=>self::NAVY]]]);
        $sheet->getStyle('A5:F5')->applyFromArray($this->cardLabelStyle());
        $sheet->getStyle('A6:F6')->applyFromArray($this->cardValueStyle());
        $sheet->getStyle('E6:F6')->getFont()->getColor()->setRGB(self::RED);
        $sheet->getStyle('A8:F8')->applyFromArray($this->headerStyle());
        $sheet->getStyle('A14:F14')->applyFromArray($this->headerStyle());
        $sheet->getStyle('A15:F16')->getAlignment()->setWrapText(true);
        $sheet->getStyle('A6:F6')->getNumberFormat()->setFormatCode(self::MONEY);
        $sheet->getRowDimension(1)->setRowHeight(34);$sheet->getRowDimension(2)->setRowHeight(24);$sheet->getRowDimension(6)->setRowHeight(30);
        foreach (range('A','F') as $column) $sheet->getColumnDimension($column)->setWidth(in_array($column,['B','D','F'])?23:19);
        $this->configureSheet($sheet, PageSetup::ORIENTATION_PORTRAIT, 'A1:F18');
    }

    private function buildCustomers($sheet, array $report): void
    {
        $sheet->setTitle('Customer Balances');
        $sheet->mergeCells('A1:G1')->setCellValue('A1','CUSTOMER ACCOUNT SUMMARY');
        $sheet->mergeCells('A2:G2')->setCellValue('A2','Posted credit invoices, customer payments and current receivables (LKR)');
        $sheet->fromArray(['Customer code','Customer name','Total invoiced','Paid amount','Invoice outstanding','Paid - not allocated','Current receivable'],null,'A4');
        $row=5;
        foreach($report['customers'] as $customer){$sheet->setCellValueExplicit('A'.$row,(string)$customer->code,DataType::TYPE_STRING);$sheet->setCellValue('B'.$row,$customer->name);$sheet->setCellValue('C'.$row,(float)$customer->total_invoiced);$sheet->setCellValue('D'.$row,(float)$customer->total_received);$sheet->setCellValue('E'.$row,(float)$customer->outstanding_balance);$sheet->setCellValue('F'.$row,(float)$customer->available_advance);$sheet->setCellValue('G'.$row,(float)$customer->current_receivable);$row++;}
        $lastData=max(4,$row-1);$sheet->setCellValue('A'.$row,'TOTAL')->mergeCells('A'.$row.':B'.$row);$sheet->setCellValue('C'.$row,$report['totals']['invoiced']);$sheet->setCellValue('D'.$row,$report['totals']['received']);$sheet->setCellValue('E'.$row,$report['totals']['outstanding']);$sheet->setCellValue('F'.$row,$report['totals']['advances']);$sheet->setCellValue('G'.$row,$report['totals']['current_receivable']);
        $sheet->getStyle('A1:G1')->applyFromArray($this->titleStyle(19));$sheet->getStyle('A2:G2')->applyFromArray(['font'=>['italic'=>true,'color'=>['rgb'=>'526174']]]);$sheet->getStyle('A4:G4')->applyFromArray($this->headerStyle());$sheet->getStyle('A'.$row.':G'.$row)->applyFromArray($this->totalStyle());
        if($lastData>=5){$sheet->getStyle('A5:G'.$lastData)->applyFromArray($this->bodyBorders());$sheet->setAutoFilter('A4:G'.$lastData);$sheet->getStyle('G5:G'.$lastData)->getFont()->getColor()->setRGB(self::RED);}
        $sheet->getStyle('C5:G'.$row)->getNumberFormat()->setFormatCode(self::MONEY);$sheet->freezePane('A5');
        foreach(['A'=>18,'B'=>34,'C'=>18,'D'=>18,'E'=>20,'F'=>18,'G'=>20] as $column=>$width)$sheet->getColumnDimension($column)->setWidth($width);
        $this->configureSheet($sheet,PageSetup::ORIENTATION_LANDSCAPE,'A1:G'.$row);
    }

    private function buildReceipts($sheet, array $report): void
    {
        $sheet->setTitle('Receipt History');$sheet->mergeCells('A1:H1')->setCellValue('A1','RECEIPT HISTORY');$sheet->mergeCells('A2:H2')->setCellValue('A2','All posted customer payments for the selected report scope');$sheet->fromArray(['Receipt','Date','Customer code','Customer','Payment method','Reference','Payment received','Applied to invoices'],null,'A4');
        $row=5;
        foreach($report['receipts'] as $receipt){$sheet->setCellValueExplicit('A'.$row,(string)$receipt->receipt_number,DataType::TYPE_STRING);$sheet->setCellValue('B'.$row,\PhpOffice\PhpSpreadsheet\Shared\Date::PHPToExcel($receipt->receipt_date));$sheet->setCellValueExplicit('C'.$row,(string)$receipt->customer->code,DataType::TYPE_STRING);$sheet->setCellValue('D'.$row,$receipt->customer->name);$sheet->setCellValue('E'.$row,str($receipt->payment_method)->headline()->toString());$sheet->setCellValue('F'.$row,$receipt->reference??'');$sheet->setCellValue('G'.$row,(float)$receipt->amount);$sheet->setCellValue('H'.$row,(float)$receipt->allocated_amount);$row++;}
        $lastData=max(4,$row-1);$sheet->setCellValue('A'.$row,'TOTAL')->mergeCells('A'.$row.':F'.$row);$sheet->setCellValue('G'.$row,(float)$report['receipts']->sum('amount'));$sheet->setCellValue('H'.$row,(float)$report['receipts']->sum('allocated_amount'));
        $sheet->getStyle('A1:H1')->applyFromArray($this->titleStyle(19));$sheet->getStyle('A2:H2')->applyFromArray(['font'=>['italic'=>true,'color'=>['rgb'=>'526174']]]);$sheet->getStyle('A4:H4')->applyFromArray($this->headerStyle());$sheet->getStyle('A'.$row.':H'.$row)->applyFromArray($this->totalStyle());
        if($lastData>=5){$sheet->getStyle('A5:H'.$lastData)->applyFromArray($this->bodyBorders());$sheet->setAutoFilter('A4:H'.$lastData);$sheet->getStyle('B5:B'.$lastData)->getNumberFormat()->setFormatCode('yyyy-mm-dd');}
        $sheet->getStyle('G5:H'.$row)->getNumberFormat()->setFormatCode(self::MONEY);$sheet->freezePane('A5');
        foreach(['A'=>22,'B'=>15,'C'=>18,'D'=>34,'E'=>22,'F'=>24,'G'=>18,'H'=>18] as $column=>$width)$sheet->getColumnDimension($column)->setWidth($width);
        $this->configureSheet($sheet,PageSetup::ORIENTATION_LANDSCAPE,'A1:H'.$row);
    }

    private function configureSheet($sheet,string $orientation,string $printArea):void{$sheet->setShowGridlines(false);$sheet->getSheetView()->setZoomScale(90);$sheet->getPageSetup()->setPaperSize(PageSetup::PAPERSIZE_A4)->setOrientation($orientation)->setFitToWidth(1)->setFitToHeight(0)->setPrintArea($printArea);$sheet->getPageMargins()->setTop(.45)->setBottom(.45)->setLeft(.3)->setRight(.3);$sheet->getHeaderFooter()->setOddFooter('&LSupun Group ERP&CConfidential business report&RPage &P of &N');}
    private function titleStyle(int $size):array{return ['font'=>['bold'=>true,'size'=>$size,'color'=>['rgb'=>'FFFFFF']],'fill'=>['fillType'=>Fill::FILL_SOLID,'startColor'=>['rgb'=>self::NAVY]],'alignment'=>['vertical'=>Alignment::VERTICAL_CENTER]];}
    private function headerStyle():array{return ['font'=>['bold'=>true,'color'=>['rgb'=>'FFFFFF']],'fill'=>['fillType'=>Fill::FILL_SOLID,'startColor'=>['rgb'=>self::NAVY]],'alignment'=>['vertical'=>Alignment::VERTICAL_CENTER],'borders'=>['bottom'=>['borderStyle'=>Border::BORDER_THIN,'color'=>['rgb'=>self::BORDER]]]];}
    private function cardLabelStyle():array{return ['font'=>['bold'=>true,'color'=>['rgb'=>'526174']],'fill'=>['fillType'=>Fill::FILL_SOLID,'startColor'=>['rgb'=>self::PALE]],'alignment'=>['horizontal'=>Alignment::HORIZONTAL_CENTER],'borders'=>['outline'=>['borderStyle'=>Border::BORDER_THIN,'color'=>['rgb'=>self::BORDER]]]];}
    private function cardValueStyle():array{return ['font'=>['bold'=>true,'size'=>15,'color'=>['rgb'=>self::NAVY]],'fill'=>['fillType'=>Fill::FILL_SOLID,'startColor'=>['rgb'=>self::PALE]],'alignment'=>['horizontal'=>Alignment::HORIZONTAL_CENTER],'borders'=>['outline'=>['borderStyle'=>Border::BORDER_THIN,'color'=>['rgb'=>self::BORDER]]]];}
    private function totalStyle():array{return ['font'=>['bold'=>true,'color'=>['rgb'=>self::NAVY]],'fill'=>['fillType'=>Fill::FILL_SOLID,'startColor'=>['rgb'=>self::LIGHT_BLUE]],'borders'=>['top'=>['borderStyle'=>Border::BORDER_MEDIUM,'color'=>['rgb'=>self::NAVY]]]];}
    private function bodyBorders():array{return ['borders'=>['bottom'=>['borderStyle'=>Border::BORDER_HAIR,'color'=>['rgb'=>self::BORDER]]]];}
}
