<?php

namespace App\Services;

use Illuminate\Support\Facades\DB;
use RuntimeException;
use ZipArchive;

class ReceivableXlsxExportService
{
    private array $sheets = [];

    public function create(array $report, int $companyId, string $generatedBy): string
    {
        if (! class_exists(ZipArchive::class)) throw new RuntimeException('The PHP ZIP extension is required to create Excel reports.');
        $company = DB::table('companies')->where('id', $companyId)->first();
        $scope = $report['selectedCustomer'] ? 'Customer: '.$report['selectedCustomer']->name.' ('.$report['selectedCustomer']->code.')' : 'All registered customers';
        $this->sheets = [$this->summarySheet($report, $company, $scope, $generatedBy), $this->customerSheet($report), $this->receiptSheet($report)];

        $base = tempnam(storage_path('app'), 'receivables-');
        if ($base === false) throw new RuntimeException('Could not create the Excel report file.');
        $path = $base.'.xlsx'; @unlink($base);
        $zip = new ZipArchive();
        if ($zip->open($path, ZipArchive::CREATE | ZipArchive::OVERWRITE) !== true) throw new RuntimeException('Could not open the Excel report file.');
        $files = ['[Content_Types].xml'=>$this->contentTypes(),'_rels/.rels'=>$this->rootRelationships(),'docProps/app.xml'=>$this->appProperties(),'docProps/core.xml'=>$this->coreProperties(),'xl/workbook.xml'=>$this->workbook(),'xl/_rels/workbook.xml.rels'=>$this->workbookRelationships(),'xl/styles.xml'=>$this->styles()];
        foreach ($files as $name => $contents) $zip->addFromString($name, $contents);
        foreach ($this->sheets as $index => $sheet) $zip->addFromString('xl/worksheets/sheet'.($index + 1).'.xml', $sheet['xml']);
        $zip->close();
        return $path;
    }

    private function summarySheet(array $report, object $company, string $scope, string $generatedBy): array
    {
        $rows = [
            1=>[['SUPUN GROUP ERP',1],['',1],['',1],['',1],['',1],['',1]],
            2=>[[($company->name ?? 'Supun Group').' - Customer Receivables Report',2],['',2],['',2],['',2],['',2],['',2]],
            3=>[[$scope,11],['',11],['',11],['',11],['',11],['',11]],
            5=>[['TOTAL CREDIT SALES',3],['',3],['TOTAL COLLECTED',3],['',3],['OUTSTANDING RECEIVABLE',3],['',3]],
            6=>[[$report['totals']['invoiced'],4],['',4],[$report['totals']['received'],4],['',4],[$report['totals']['outstanding'],12],['',12]],
            8=>[['REPORT INFORMATION',5],['',5],['',5],['',5],['',5],['',5]],
            9=>[['Generated at',6],[now()->format('d M Y, H:i'),6],['',6],['',6],['',6],['',6]],
            10=>[['Generated by',6],[$generatedBy,6],['',6],['',6],['',6],['',6]],
            11=>[['Customer accounts',6],[$report['customers']->count(),6],['',6],['',6],['',6],['',6]],
            12=>[['Posted receipts',6],[$report['receipts']->count(),6],['',6],['',6],['',6],['',6]],
            14=>[['NOTES',5],['',5],['',5],['',5],['',5],['',5]],
            15=>[['This report includes posted credit invoices and posted customer receipts for the selected scope.',11],['',11],['',11],['',11],['',11],['',11]],
            16=>[['Amounts are in Sri Lankan Rupees (LKR). Supporting details are available in the other worksheets.',11],['',11],['',11],['',11],['',11],['',11]],
        ];
        $merges=['A1:F1','A2:F2','A3:F3','A5:B5','C5:D5','E5:F5','A6:B6','C6:D6','E6:F6','A8:F8','B9:F9','B10:F10','B11:F11','B12:F12','A14:F14','A15:F15','A16:F16'];
        return ['name'=>'Summary','xml'=>$this->sheetXml($rows,[18,24,18,24,22,24],$merges,null,0,'portrait')];
    }

    private function customerSheet(array $report): array
    {
        $rows=[1=>[['CUSTOMER ACCOUNT SUMMARY',1],['',1],['',1],['',1],['',1]],2=>[['Posted invoice, receipt and outstanding balances (LKR)',2],['',2],['',2],['',2],['',2]],4=>[['Customer code',5],['Customer name',5],['Total invoiced',5],['Total received',5],['Outstanding',5]]];
        $row=5;
        foreach($report['customers'] as $customer)$rows[$row++]=[[(string)$customer->code,6],[(string)$customer->name,6],[(float)$customer->total_invoiced,8],[(float)$customer->total_received,8],[(float)$customer->outstanding_balance,(float)$customer->outstanding_balance>0?12:8]];
        $last=max(4,$row-1); $rows[$row]=[['TOTAL',9],['',9],[$report['totals']['invoiced'],10],[$report['totals']['received'],10],[$report['totals']['outstanding'],10]];
        return ['name'=>'Customer Balances','xml'=>$this->sheetXml($rows,[18,38,20,20,20],['A1:E1','A2:E2','A'.$row.':B'.$row],'A4:E'.$last,4,'landscape')];
    }

    private function receiptSheet(array $report): array
    {
        $rows=[1=>[['RECEIPT HISTORY',1],['',1],['',1],['',1],['',1],['',1],['',1],['',1]],2=>[['All posted customer receipts for the selected report scope',2],['',2],['',2],['',2],['',2],['',2],['',2],['',2]],4=>[['Receipt',5],['Date',5],['Customer code',5],['Customer',5],['Payment method',5],['Reference',5],['Amount',5],['Unapplied',5]]];
        $row=5;
        foreach($report['receipts'] as $receipt)$rows[$row++]=[[(string)$receipt->receipt_number,6],[($receipt->receipt_date->copy()->startOfDay()->timestamp/86400)+25569,7],[(string)$receipt->customer->code,6],[(string)$receipt->customer->name,6],[str($receipt->payment_method)->headline()->toString(),6],[(string)($receipt->reference??''),6],[(float)$receipt->amount,8],[(float)$receipt->unapplied_amount,8]];
        $last=max(4,$row-1); $rows[$row]=[['TOTAL',9],['',9],['',9],['',9],['',9],['',9],[(float)$report['receipts']->sum('amount'),10],[(float)$report['receipts']->sum('unapplied_amount'),10]];
        return ['name'=>'Receipt History','xml'=>$this->sheetXml($rows,[22,15,18,34,22,24,18,18],['A1:H1','A2:H2','A'.$row.':F'.$row],'A4:H'.$last,4,'landscape')];
    }

    private function sheetXml(array $rows,array $widths,array $merges,?string $filter,int $freeze,string $orientation):string
    {
        $cols=''; foreach($widths as $i=>$width)$cols.='<col min="'.($i+1).'" max="'.($i+1).'" width="'.$width.'" customWidth="1"/>';
        $body=''; foreach($rows as $r=>$cells){$body.='<row r="'.$r.'" ht="'.(in_array($r,[1,2,5,6],true)?26:20).'" customHeight="1">';foreach($cells as $c=>[$value,$style])$body.=$this->cell($c,$r,$value,$style);$body.='</row>';}
        $mergeXml=$merges?'<mergeCells count="'.count($merges).'">'.implode('',array_map(fn($x)=>'<mergeCell ref="'.$x.'"/>',$merges)).'</mergeCells>':'';
        $view=$freeze?'<sheetViews><sheetView workbookViewId="0" showGridLines="0"><pane ySplit="'.$freeze.'" topLeftCell="A'.($freeze+1).'" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews>':'<sheetViews><sheetView workbookViewId="0" showGridLines="0"/></sheetViews>';
        return '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetPr><pageSetUpPr fitToPage="1"/></sheetPr>'.$view.'<sheetFormatPr defaultRowHeight="20"/><cols>'.$cols.'</cols><sheetData>'.$body.'</sheetData>'.$mergeXml.($filter?'<autoFilter ref="'.$filter.'"/>':'').'<pageMargins left="0.3" right="0.3" top="0.5" bottom="0.5" header="0.2" footer="0.2"/><pageSetup orientation="'.$orientation.'" paperSize="9" fitToWidth="1" fitToHeight="0"/></worksheet>';
    }

    private function cell(int $column,int $row,mixed $value,int $style):string
    {
        $ref=$this->columnName($column+1).$row;
        if(is_int($value)||is_float($value))return '<c r="'.$ref.'" s="'.$style.'"><v>'.$value.'</v></c>';
        return '<c r="'.$ref.'" s="'.$style.'" t="inlineStr"><is><t xml:space="preserve">'.$this->escape((string)$value).'</t></is></c>';
    }

    private function columnName(int $number):string{$name='';while($number>0){$number--;$name=chr(65+($number%26)).$name;$number=intdiv($number,26);}return $name;}
    private function escape(string $value):string{return htmlspecialchars($value,ENT_XML1|ENT_QUOTES,'UTF-8');}

    private function contentTypes():string{$s='';foreach($this->sheets as $i=>$_)$s.='<Override PartName="/xl/worksheets/sheet'.($i+1).'.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>';return '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/><Override PartName="/docProps/core.xml" ContentType="application/vnd.openxmlformats-package.core-properties+xml"/><Override PartName="/docProps/app.xml" ContentType="application/vnd.openxmlformats-officedocument.extended-properties+xml"/>'.$s.'</Types>';}
    private function rootRelationships():string{return '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties" Target="docProps/core.xml"/><Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/extended-properties" Target="docProps/app.xml"/></Relationships>';}
    private function workbook():string{$s='';foreach($this->sheets as $i=>$sheet)$s.='<sheet name="'.$this->escape($sheet['name']).'" sheetId="'.($i+1).'" r:id="rId'.($i+2).'"/>';return '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><bookViews><workbookView/></bookViews><sheets>'.$s.'</sheets><calcPr calcId="191029" fullCalcOnLoad="1"/></workbook>';}
    private function workbookRelationships():string{$r='<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/>';foreach($this->sheets as $i=>$_)$r.='<Relationship Id="rId'.($i+2).'" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet'.($i+1).'.xml"/>';return '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'.$r.'</Relationships>';}
    private function appProperties():string{$titles=implode('',array_map(fn($s)=>'<vt:lpstr>'.$this->escape($s['name']).'</vt:lpstr>',$this->sheets));return '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/extended-properties" xmlns:vt="http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes"><Application>Supun Group ERP</Application><TitlesOfParts><vt:vector size="'.count($this->sheets).'" baseType="lpstr">'.$titles.'</vt:vector></TitlesOfParts></Properties>';}
    private function coreProperties():string{return '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><cp:coreProperties xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dcterms="http://purl.org/dc/terms/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><dc:title>Customer Receivables Report</dc:title><dc:creator>Supun Group ERP</dc:creator><dcterms:created xsi:type="dcterms:W3CDTF">'.now()->utc()->format('Y-m-d\TH:i:s\Z').'</dcterms:created></cp:coreProperties>';}

    private function styles():string
    {
        return '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><numFmts count="2"><numFmt numFmtId="164" formatCode="&quot;Rs. &quot;#,##0.00;[Red]-&quot;Rs. &quot;#,##0.00"/><numFmt numFmtId="165" formatCode="yyyy-mm-dd"/></numFmts><fonts count="6"><font><sz val="11"/><name val="Aptos"/></font><font><b/><sz val="20"/><color rgb="FFFFFFFF"/><name val="Aptos Display"/></font><font><b/><sz val="13"/><color rgb="FF17396B"/><name val="Aptos"/></font><font><b/><sz val="10"/><color rgb="FF526174"/><name val="Aptos"/></font><font><b/><sz val="15"/><color rgb="FF17396B"/><name val="Aptos Display"/></font><font><b/><sz val="15"/><color rgb="FFD92D3A"/><name val="Aptos Display"/></font></fonts><fills count="6"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FF17396B"/></patternFill></fill><fill><patternFill patternType="solid"><fgColor rgb="FFF2F6FB"/></patternFill></fill><fill><patternFill patternType="solid"><fgColor rgb="FFEAF1FA"/></patternFill></fill><fill><patternFill patternType="solid"><fgColor rgb="FFFFECEE"/></patternFill></fill></fills><borders count="3"><border><left/><right/><top/><bottom/><diagonal/></border><border><left/><right/><top/><bottom style="thin"><color rgb="FFDDE5EE"/></bottom><diagonal/></border><border><left style="thin"><color rgb="FFDDE5EE"/></left><right style="thin"><color rgb="FFDDE5EE"/></right><top style="thin"><color rgb="FFDDE5EE"/></top><bottom style="thin"><color rgb="FFDDE5EE"/></bottom><diagonal/></border></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="13"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/><xf numFmtId="0" fontId="1" fillId="2" borderId="0" xfId="0" applyFont="1" applyFill="1"/><xf numFmtId="0" fontId="2" fillId="0" borderId="0" xfId="0" applyFont="1"/><xf numFmtId="0" fontId="3" fillId="3" borderId="2" xfId="0" applyFont="1" applyFill="1" applyBorder="1" applyAlignment="1"><alignment horizontal="center"/></xf><xf numFmtId="164" fontId="4" fillId="3" borderId="2" xfId="0" applyNumberFormat="1" applyFont="1" applyFill="1" applyBorder="1" applyAlignment="1"><alignment horizontal="center"/></xf><xf numFmtId="0" fontId="1" fillId="2" borderId="0" xfId="0" applyFont="1" applyFill="1"/><xf numFmtId="0" fontId="0" fillId="0" borderId="1" xfId="0" applyBorder="1"/><xf numFmtId="165" fontId="0" fillId="0" borderId="1" xfId="0" applyNumberFormat="1" applyBorder="1"/><xf numFmtId="164" fontId="0" fillId="0" borderId="1" xfId="0" applyNumberFormat="1" applyBorder="1" applyAlignment="1"><alignment horizontal="right"/></xf><xf numFmtId="0" fontId="3" fillId="4" borderId="0" xfId="0" applyFont="1" applyFill="1"/><xf numFmtId="164" fontId="2" fillId="4" borderId="0" xfId="0" applyNumberFormat="1" applyFont="1" applyFill="1" applyAlignment="1"><alignment horizontal="right"/></xf><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0" applyAlignment="1"><alignment wrapText="1" vertical="top"/></xf><xf numFmtId="164" fontId="5" fillId="5" borderId="2" xfId="0" applyNumberFormat="1" applyFont="1" applyFill="1" applyBorder="1" applyAlignment="1"><alignment horizontal="center"/></xf></cellXfs><cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles></styleSheet>';
    }
}
