@extends('layouts.app')
@section('title','Bill to Invoice')
@push('styles')<style>.direct-sheet input,.direct-sheet select{min-width:140px}.direct-sheet .product-cell{min-width:280px}.direct-sheet .serial-cell{min-width:260px}.direct-sheet tfoot td{background:#f8fafc;font-weight:700}</style>@endpush
@section('content')
<div class="d-flex justify-content-between align-items-start mb-4"><div><h1 class="h3 page-title mb-1">Bill to Invoice</h1><p class="text-muted mb-0">Post a direct supplier purchase without creating a Purchase Order first.</p></div><a class="btn btn-outline-secondary" href="{{ route('purchase-orders.index') }}">Purchase Orders</a></div>
<form method="POST" action="{{ route('purchases.direct.store') }}" id="direct-purchase-form">@csrf
<div class="card mb-4"><div class="card-body p-4"><div class="row g-3">
<div class="col-md-4"><label class="form-label">Supplier</label><select class="form-select" name="supplier_id" required><option value="">Select supplier</option>@foreach($suppliers as $supplier)<option value="{{ $supplier->id }}" @selected(old('supplier_id')==$supplier->id)>{{ $supplier->code }} — {{ $supplier->name }}</option>@endforeach</select></div>
<div class="col-md-3"><label class="form-label">Supplier bill / invoice no.</label><input class="form-control" name="supplier_invoice_number" value="{{ old('supplier_invoice_number') }}" required></div>
<div class="col-md-2"><label class="form-label">Invoice date</label><input class="form-control" type="date" name="invoice_date" value="{{ old('invoice_date',date('Y-m-d')) }}" required></div>
<div class="col-md-2"><label class="form-label">Due date</label><input class="form-control" type="date" name="due_date" value="{{ old('due_date') }}"></div>
<div class="col-md-4"><label class="form-label">Stock location</label><select class="form-select" name="stock_location_id" required>@foreach($locations as $location)<option value="{{ $location->id }}" @selected(old('stock_location_id',$location->is_default?$location->id:null)==$location->id)>{{ $location->code }} — {{ $location->name }}</option>@endforeach</select></div>
<div class="col-md-8"><label class="form-label">Notes</label><input class="form-control" name="notes" value="{{ old('notes') }}"></div>
</div></div></div>
<div class="card"><div class="card-header p-3 d-flex justify-content-between align-items-center"><div><strong>Purchased items</strong><div class="small text-muted">Enter the products exactly as shown on the supplier bill.</div></div><div class="d-flex gap-2"><button class="btn btn-outline-secondary btn-sm" type="button" id="refresh-products" title="Load newly created products"><i class="bi bi-arrow-clockwise"></i> Refresh products</button><button class="btn btn-outline-primary btn-sm" type="button" id="add-line"><i class="bi bi-plus-lg"></i> Add line</button></div></div><div class="table-responsive"><table class="table align-middle mb-0 direct-sheet" id="direct-items"><thead><tr><th class="ps-3">Product</th><th>Quantity</th><th>Unit cost</th><th>Line total</th><th>Serial numbers</th><th></th></tr></thead><tbody></tbody><tfoot><tr><td colspan="3" class="text-end">Invoice total</td><td id="invoice-total">Rs. 0.00</td><td colspan="2"></td></tr></tfoot></table></div><div class="card-footer p-3 text-end"><button class="btn btn-success px-4" onclick="return confirm('Post this direct purchase invoice and update stock?')"><i class="bi bi-receipt me-1"></i>Post Purchase Invoice</button></div></div>
</form>
<template id="direct-line-template"><tr><td class="ps-3"><select class="form-select product-cell" data-field="product_id" required><option value="">Select product</option><option value="__create__">＋ Create new product…</option>@foreach($products as $product)<option value="{{ $product->id }}" data-cost="{{ $product->average_cost }}" data-serial="{{ $product->serial_tracking?1:0 }}">{{ $product->item_code }} — {{ $product->name }}</option>@endforeach</select></td><td><input class="form-control quantity" data-field="quantity" type="number" min="0.0001" step="0.0001" value="1" required></td><td><input class="form-control unit-cost" data-field="unit_cost" type="number" min="0" step="0.0001" value="0" required></td><td class="line-total fw-semibold">0.00</td><td><textarea class="form-control serial-cell" data-field="serials" rows="1" placeholder="Optional; comma/newline separated"></textarea></td><td><button class="btn btn-light text-danger remove-line" type="button"><i class="bi bi-trash"></i></button></td></tr></template>
@endsection
@push('scripts')<script>(()=>{const body=document.querySelector('#direct-items tbody'),template=document.getElementById('direct-line-template'),old=@json(old('items',[])),selected=@json($selectedProducts->map(fn($p)=>['product_id'=>$p->id,'quantity'=>1,'unit_cost'=>$p->average_cost])->values()),createUrl=@json(route('products.create')),optionsUrl=@json(route('purchases.direct.product-options'));let index=0;const refresh=()=>{let total=0;[...body.rows].forEach((row,i)=>{row.querySelectorAll('[data-field]').forEach(el=>el.name=`items[${i}][${el.dataset.field}]`);const line=Number(row.querySelector('.quantity').value||0)*Number(row.querySelector('.unit-cost').value||0);row.querySelector('.line-total').textContent=line.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});total+=line});document.getElementById('invoice-total').textContent='Rs. '+total.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})};const add=(values={})=>{const row=template.content.firstElementChild.cloneNode(true);row.querySelectorAll('[data-field]').forEach(el=>{if(values[el.dataset.field]!==undefined)el.value=values[el.dataset.field]});const product=row.querySelector('.product-cell'),serial=row.querySelector('.serial-cell');const updateProduct=()=>{const option=product.selectedOptions[0];serial.disabled=option?.dataset.serial!=='1'};product.onchange=()=>{if(product.value==='__create__'){product.value='';window.open(createUrl,'_blank','noopener');return}const option=product.selectedOptions[0];if(option?.dataset.cost!==undefined)row.querySelector('.unit-cost').value=Number(option.dataset.cost);updateProduct();refresh()};updateProduct();row.querySelectorAll('.quantity,.unit-cost').forEach(el=>el.oninput=refresh);row.querySelector('.remove-line').onclick=()=>{if(body.rows.length>1)row.remove();refresh()};body.append(row);index++;refresh()};(old.length?old:(selected.length?selected:[{}])).forEach(add);document.getElementById('add-line').onclick=()=>add();document.getElementById('refresh-products').onclick=async e=>{const button=e.currentTarget,html=button.innerHTML;button.disabled=true;button.innerHTML='<span class="spinner-border spinner-border-sm"></span> Loading';try{const products=await fetch(optionsUrl,{headers:{Accept:'application/json'}}).then(r=>{if(!r.ok)throw new Error();return r.json()});body.querySelectorAll('.product-cell').forEach(select=>{const value=select.value;select.replaceChildren(new Option('Select product',''),new Option('＋ Create new product…','__create__'));products.forEach(p=>{const option=new Option(p.label,p.id);option.dataset.cost=p.cost;option.dataset.serial=p.serial_tracking?1:0;select.add(option)});select.value=value});button.innerHTML='<i class="bi bi-check2"></i> Products refreshed';setTimeout(()=>button.innerHTML=html,1500)}catch{button.innerHTML='<i class="bi bi-exclamation-triangle"></i> Try again'}finally{button.disabled=false}}})();</script>@endpush
