@extends('layouts.app')
@section('title',$backdatedInvoice->request_number)
@section('content')
@php($isCredit=($payload['payment_type']??'credit')==='credit')
<div class="d-flex justify-content-between align-items-start gap-3 mb-4"><div><a href="{{ route('backdated-invoices.index') }}" class="text-decoration-none">&larr; Backdated invoices</a><h1 class="h3 page-title mt-2 mb-1">{{ $backdatedInvoice->request_number }}</h1><p class="text-muted mb-0">Review all invoice details before approval.</p></div><span class="badge fs-6 {{ $backdatedInvoice->status==='approved'?'bg-success':($backdatedInvoice->status==='rejected'?'bg-danger':'bg-warning text-dark') }}">{{ ucfirst($backdatedInvoice->status) }}</span></div>
<div class="row g-3 mb-3">
    <div class="col-md-3"><div class="card h-100"><div class="card-body"><small class="text-muted">Sale type</small><div class="fw-bold fs-5">{{ $isCredit?'Credit Sale':'Cash Sale' }}</div></div></div></div>
    <div class="col-md-3"><div class="card h-100"><div class="card-body"><small class="text-muted">Invoice date</small><div class="fw-bold fs-5">{{ $backdatedInvoice->invoice_date->format('d M Y') }}</div></div></div></div>
    <div class="col-md-3"><div class="card h-100"><div class="card-body"><small class="text-muted">Submitted</small><div class="fw-bold">{{ $backdatedInvoice->submitted_at->format('d M Y, h:i A') }}</div><small>{{ $backdatedInvoice->requester?->name }}</small></div></div></div>
    <div class="col-md-3"><div class="card h-100"><div class="card-body"><small class="text-muted">Grand total</small><div class="fw-bold fs-5">Rs. {{ number_format($backdatedInvoice->total_amount,2) }}</div></div></div></div>
</div>
<div class="card mb-3"><div class="card-body"><div class="row g-3"><div class="col-md-6"><small class="text-muted">Customer</small><div class="fw-bold">{{ $customer?->is_walk_in?($payload['walk_in_customer_name']?:'Temporary Cash Customer'):($customer?->name??'Unknown customer') }}</div>@if($customer&&!$customer->is_walk_in)<div class="small text-muted">{{ $customer->code }}</div>@endif</div><div class="col-md-3"><small class="text-muted">Pricing channel</small><div class="fw-bold">{{ str($payload['channel']??'retail')->headline() }}</div></div><div class="col-md-3"><small class="text-muted">Payment details</small><div class="fw-bold">{{ $isCredit?'Due '.(isset($payload['due_date'])?now()->parse($payload['due_date'])->format('d M Y'):'Not set'):str($payload['payment_method']??'cash')->headline() }}</div></div></div></div></div>
<div class="card mb-3"><div class="table-responsive"><table class="table mb-0 align-middle"><thead><tr><th>Item</th><th class="text-end">Quantity</th><th class="text-end">Unit price</th><th class="text-end">Line total</th></tr></thead><tbody>
@foreach($payload['items']??[] as $item) @php($product=$products->get($item['product_id']??null)) @php($line=(float)($item['quantity']??0)*(float)($item['unit_price']??0))
<tr><td><strong>{{ $product?->name??'Product unavailable' }}</strong><div class="small text-muted">{{ $product?->item_code }}</div></td><td class="text-end">{{ rtrim(rtrim(number_format((float)($item['quantity']??0),4,'.',''), '0'), '.') }}</td><td class="text-end">Rs. {{ number_format((float)($item['unit_price']??0),2) }}</td><td class="text-end fw-bold">Rs. {{ number_format($line,2) }}</td></tr>
@endforeach
</tbody><tfoot><tr><th colspan="3" class="text-end">Discount</th><th class="text-end">Rs. {{ number_format((float)($payload['discount_amount']??0),2) }}</th></tr><tr><th colspan="3" class="text-end">Grand total</th><th class="text-end fs-5">Rs. {{ number_format($backdatedInvoice->total_amount,2) }}</th></tr></tfoot></table></div></div>
@if($payload['notes']??null)<div class="card mb-3"><div class="card-body"><small class="text-muted">Notes</small><div>{{ $payload['notes'] }}</div></div></div>@endif
@if($backdatedInvoice->status==='pending'&&auth()->user()->hasPermission('backdated_invoices.approve'))<div class="d-flex gap-2 justify-content-end"><form method="POST" action="{{ route('backdated-invoices.reject',$backdatedInvoice) }}">@csrf<button class="btn btn-outline-danger">Reject Request</button></form><form method="POST" action="{{ route('backdated-invoices.approve',$backdatedInvoice) }}">@csrf<button class="btn btn-success" onclick="return confirm('Approve and post this invoice?')"><i class="bi bi-check-circle"></i> Approve and Post</button></form></div>@endif
@endsection
