<?php
namespace Tests\Feature;
use App\Models\{Product,User};use App\Services\SalesDocumentWorkflowService;use Database\Seeders\DatabaseSeeder;use Illuminate\Foundation\Testing\RefreshDatabase;use Illuminate\Support\Facades\DB;use Tests\TestCase;
class PhaseElevenDocumentWorkflowTest extends TestCase
{
 use RefreshDatabase;
 public function test_quotation_converts_and_partial_deliveries_create_traceable_invoices():void{$this->seed(DatabaseSeeder::class);$u=User::where('email','admin@supun-erp.local')->first();$c=$u->company_id;$cat=DB::table('product_categories')->insertGetId(['company_id'=>$c,'code'=>'DOC','name'=>'Documents','is_active'=>1,'created_at'=>now(),'updated_at'=>now()]);$p=Product::create(['company_id'=>$c,'product_category_id'=>$cat,'unit_id'=>DB::table('units')->where('code','PCS')->value('id'),'item_code'=>'DOC-1','name'=>'Workflow Product','average_cost'=>50,'current_quantity'=>10,'minimum_stock'=>0,'reorder_level'=>0,'warranty_months'=>0,'serial_tracking'=>0,'is_active'=>1]);$customer=DB::table('customers')->where('code','WALK-IN')->value('id');$service=app(SalesDocumentWorkflowService::class);$quote=$service->createQuotation(['customer_id'=>$customer,'quotation_date'=>now()->toDateString(),'valid_until'=>now()->addWeek()->toDateString(),'channel'=>'wholesale','discount_amount'=>40,'items'=>[['product_id'=>$p->id,'quantity'=>4,'unit_price'=>100]]],$u);$order=$service->convertToOrder($quote,$u);$item=$order->items()->first();$first=$service->deliverAndInvoice($order,['payment_type'=>'credit','due_date'=>now()->addMonth()->toDateString(),'paid_amount'=>0,'payment_method'=>'cash','items'=>[$item->id=>['quantity'=>2]]],$u);$this->assertSame('partially_delivered',$order->fresh()->status);$this->assertEqualsWithDelta(8,(float)$p->fresh()->current_quantity,.0001);$this->assertEquals(180,(float)$first->sale->grand_total);$second=$service->deliverAndInvoice($order,['payment_type'=>'credit','due_date'=>now()->addMonth()->toDateString(),'paid_amount'=>0,'payment_method'=>'cash','items'=>[$item->id=>['quantity'=>2]]],$u);$this->assertSame('completed',$order->fresh()->status);$this->assertEqualsWithDelta(6,(float)$p->fresh()->current_quantity,.0001);$this->assertEquals(2,$order->deliveries()->count());$this->assertNotNull($first->sale_id);$this->assertNotNull($second->sale_id);$this->assertDatabaseHas('quotations',['id'=>$quote->id,'status'=>'converted']);$this->assertDatabaseHas('sales_order_items',['id'=>$item->id,'delivered_quantity'=>4]);}
 public function test_document_workflow_pages_open_for_authorized_user():void{$this->seed(DatabaseSeeder::class);$u=User::where('email','admin@supun-erp.local')->first();foreach(['/quotations','/quotations/create','/sales-orders','/delivery-notes'] as $url)$this->actingAs($u)->get($url)->assertOk();}
}
