@extends('layouts.app')
@section('title','All Payables')
@section('content')
<div class="d-flex justify-content-between align-items-start gap-3 flex-wrap mb-4"><div><h1 class="h3 page-title mb-1">All Payables</h1><p class="text-muted mb-0">Every amount currently owed to suppliers and expense service providers.</p></div><a href="{{ route('payables.all.export') }}" class="btn btn-outline-success"><i class="bi bi-file-earmark-excel me-1"></i>Download Excel</a></div>
<div class="row g-3 mb-4"><div class="col-md-4"><div class="card h-100 border-start border-primary border-4"><div class="card-body"><div class="text-muted">Supplier payables</div><div class="h3 mb-0">Rs. {{ number_format($supplierPayable,2) }}</div></div></div></div><div class="col-md-4"><div class="card h-100 border-start border-warning border-4"><div class="card-body"><div class="text-muted">Expense payables</div><div class="h3 mb-0">Rs. {{ number_format($expensePayable,2) }}</div></div></div></div><div class="col-md-4"><div class="card h-100 border-start border-danger border-4"><div class="card-body"><div class="text-muted">Full outstanding payable</div><div class="h3 mb-0 text-danger">Rs. {{ number_format($supplierPayable+$expensePayable,2) }}</div></div></div></div></div>

<div class="card mb-4"><div class="card-header bg-white p-3 d-flex justify-content-between align-items-center"><div><div class="fw-semibold">Supplier payables</div><small class="text-muted">Includes supplier opening balances, posted purchase bills, payments and debit notes.</small></div><a href="{{ route('payables.index') }}" class="btn btn-sm btn-outline-primary">Supplier payables</a></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th class="ps-4">Supplier</th><th>Code</th><th class="text-end">Total billed</th><th class="text-end">Paid</th><th class="text-end">Payable</th><th class="text-end pe-4">Action</th></tr></thead><tbody>@forelse($suppliers as $supplier)<tr><td class="ps-4 fw-semibold">{{ $supplier->name }}</td><td>{{ $supplier->code }}</td><td class="text-end">{{ number_format($supplier->total_invoiced,2) }}</td><td class="text-end text-success">{{ number_format($supplier->total_paid,2) }}</td><td class="text-end text-danger fw-semibold">{{ number_format($supplier->current_payable,2) }}</td><td class="text-end pe-4"><a class="btn btn-sm btn-outline-dark" href="{{ route('payables.ledger',$supplier) }}">View ledger</a> <a class="btn btn-sm btn-primary" href="{{ route('payables.create',['supplier_id'=>$supplier->id]) }}">Pay</a></td></tr>@empty<tr><td colspan="6" class="text-center text-muted py-4">No outstanding supplier payables.</td></tr>@endforelse</tbody></table></div></div>

<div class="card"><div class="card-header bg-white p-3 d-flex justify-content-between align-items-center"><div><div class="fw-semibold">Expense payables</div><small class="text-muted">Unpaid electricity, rent, utilities and other operating-expense bills.</small></div><a href="{{ route('expenses.index') }}" class="btn btn-sm btn-outline-primary">Expense bills</a></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th class="ps-4">Bill</th><th>Payee</th><th>Account</th><th>Due date</th><th class="text-end">Bill amount</th><th class="text-end">Paid</th><th class="text-end">Payable</th><th class="text-end pe-4">Action</th></tr></thead><tbody>@forelse($expenses as $expense)<tr><td class="ps-4"><a class="fw-semibold text-decoration-none" href="{{ route('expenses.show',$expense) }}">{{ $expense->document_number }}</a><div class="small text-muted">{{ $expense->billing_period }}</div></td><td>{{ $expense->payee }}</td><td>{{ $expense->account->name }}</td><td class="{{ $expense->due_date&&$expense->due_date->isPast()?'text-danger fw-semibold':'' }}">{{ optional($expense->due_date)->format('d M Y')?:'—' }}</td><td class="text-end">{{ number_format($expense->amount,2) }}</td><td class="text-end text-success">{{ number_format($expense->paid_amount,2) }}</td><td class="text-end text-danger fw-semibold">{{ number_format($expense->balance_amount,2) }}</td><td class="text-end pe-4"><a class="btn btn-sm btn-outline-dark" href="{{ route('expenses.show',$expense) }}">View</a> <a class="btn btn-sm btn-primary" href="{{ route('expenses.payment',$expense) }}">Pay</a></td></tr>@empty<tr><td colspan="8" class="text-center text-muted py-4">No outstanding expense payables.</td></tr>@endforelse</tbody></table></div></div>
@endsection
