@extends('layouts.app')
@section('title','Payables')
@section('content')
<div class="d-flex justify-content-between mb-4"><div><h1 class="h3 page-title">Supplier Payables</h1><p class="text-muted">Open a row action to pay, inspect its GRN, or review the supplier ledger.</p></div><div><a href="{{ route('payables.aging') }}" class="btn btn-outline-primary">Aging</a> <a href="{{ route('payables.create') }}" class="btn btn-primary">New Payment</a></div></div>
@php($payableTotals=\App\Models\SupplierInvoice::where('company_id',auth()->user()->company_id)->where('status','posted')->selectRaw('COALESCE(SUM(total_amount),0) billed, COALESCE(SUM(total_amount-balance_amount),0) paid, COALESCE(SUM(balance_amount),0) outstanding')->first())
<div class="row g-3 mb-4">
    <div class="col-md-4"><div class="card h-100"><div class="card-body"><div class="text-muted mb-1">Total supplier bills</div><div class="h3 mb-0">Rs. {{ number_format((float)$payableTotals->billed,2) }}</div></div></div></div>
    <div class="col-md-4"><div class="card h-100 border-start border-success border-4"><div class="card-body"><div class="text-muted mb-1">Total paid</div><div class="h3 mb-0 text-success">Rs. {{ number_format((float)$payableTotals->paid,2) }}</div></div></div></div>
    <div class="col-md-4"><div class="card h-100 border-start border-danger border-4"><div class="card-body"><div class="text-muted mb-1">Outstanding payable</div><div class="h3 mb-0 text-danger">Rs. {{ number_format((float)$payableTotals->outstanding,2) }}</div></div></div></div>
</div>
<div class="card"><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th class="ps-4">Invoice</th><th>Supplier</th><th>Date</th><th>Due</th><th class="text-end">Total</th><th class="text-end">Balance</th><th>Status</th><th class="text-end pe-4">Actions</th></tr></thead><tbody>@forelse($invoices as $invoice)<tr><td class="ps-4"><strong>{{ $invoice->document_number }}</strong><div class="small text-muted">Supplier ref: {{ $invoice->supplier_invoice_number ?: '—' }}</div></td><td>{{ $invoice->supplier->name }}</td><td>{{ $invoice->invoice_date->format('d M Y') }}</td><td class="{{ $invoice->due_date&&$invoice->due_date->isPast()&&(float)$invoice->balance_amount>0?'text-danger fw-semibold':'' }}">{{ optional($invoice->due_date)->format('d M Y') ?: '—' }}</td><td class="text-end">{{ number_format($invoice->total_amount,2) }}</td><td class="text-end fw-semibold">{{ number_format($invoice->balance_amount,2) }}</td><td><span class="badge text-bg-{{ $invoice->payment_status==='paid'?'success':($invoice->payment_status==='unpaid'?'danger':'warning') }}">{{ str($invoice->payment_status)->headline() }}</span></td><td class="text-end pe-4"><div class="dropdown"><button class="btn btn-sm btn-outline-primary dropdown-toggle" data-bs-toggle="dropdown">Actions</button><ul class="dropdown-menu dropdown-menu-end">@if((float)$invoice->balance_amount>0)<li><a class="dropdown-item fw-semibold" href="{{ route('payables.create',['invoice_id'=>$invoice->id]) }}"><i class="bi bi-wallet2 me-2"></i>Pay this bill</a></li>@endif<li><a class="dropdown-item" href="{{ route('payables.ledger',$invoice->supplier) }}"><i class="bi bi-journal-text me-2"></i>Supplier ledger</a></li>@if($invoice->grn)<li><a class="dropdown-item" href="{{ route('grn.show',$invoice->grn) }}"><i class="bi bi-box-arrow-in-down me-2"></i>Source GRN</a></li>@endif</ul></div></td></tr>@empty<tr><td colspan="8" class="text-center text-muted py-5">No supplier invoices yet.</td></tr>@endforelse</tbody></table></div><div class="p-3">{{ $invoices->links() }}</div></div>
@endsection
