@extends('layouts.app')
@section('title','New Expense Bill')
@section('content')
<div class="mb-4"><h1 class="h3 page-title mb-1">New Expense Bill</h1><p class="text-muted mb-0">Record the full bill and any amount paid now. The unpaid amount remains payable.</p></div>
<form method="POST" action="{{ route('expenses.store') }}" id="expense-form">@csrf<div class="card"><div class="card-body p-4"><div class="row g-3">
<div class="col-md-3"><label class="form-label">Bill date</label><input type="date" name="expense_date" value="{{ old('expense_date',now()->toDateString()) }}" class="form-control" required></div><div class="col-md-3"><label class="form-label">Due date</label><input type="date" name="due_date" value="{{ old('due_date') }}" class="form-control"></div><div class="col-md-3"><label class="form-label">Expense account</label><select name="account_id" class="form-select" required>@foreach($accounts as $account)<option value="{{ $account->id }}" @selected(old('account_id')==$account->id)>{{ $account->code }} — {{ $account->name }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label">Bill amount</label><input id="bill-amount" type="number" step=".01" min=".01" name="amount" value="{{ old('amount') }}" class="form-control" required></div>
<div class="col-md-4"><label class="form-label">Payee / service provider</label><input name="payee" value="{{ old('payee') }}" class="form-control" placeholder="e.g. Electricity Board" required></div><div class="col-md-3"><label class="form-label">Amount paid now</label><input id="paid-amount" type="number" step=".01" min="0" name="paid_amount" value="{{ old('paid_amount',0) }}" class="form-control" required></div><div class="col-md-3"><label class="form-label">Payment method</label><select id="payment-method" name="payment_method" class="form-select"><option value="">Not paid yet</option>@foreach(['cash'=>'Cash','bank_transfer'=>'Bank transfer','cheque'=>'Cheque','online_payment'=>'Online payment'] as $value=>$label)<option value="{{ $value }}" @selected(old('payment_method')===$value)>{{ $label }}</option>@endforeach</select></div><div class="col-md-2"><label class="form-label">Reference</label><input name="reference" value="{{ old('reference') }}" class="form-control"></div>
<div class="col-12"><div class="alert alert-info mb-0 d-flex justify-content-between"><span>Outstanding payable after posting</span><strong id="balance-preview">Rs. 0.00</strong></div></div><div class="col-12"><label class="form-label">Description</label><textarea name="description" class="form-control" required>{{ old('description') }}</textarea></div><div class="col-12 text-end"><button class="btn btn-primary px-4">Post Expense Bill</button></div>
</div></div></div></form>
@endsection
@push('scripts')<script>(()=>{const bill=document.getElementById('bill-amount'),paid=document.getElementById('paid-amount'),method=document.getElementById('payment-method'),preview=document.getElementById('balance-preview');const update=()=>{const total=Number(bill.value||0),settled=Number(paid.value||0);paid.max=total||'';method.required=settled>0;method.disabled=settled<=0;if(settled<=0)method.value='';preview.textContent='Rs. '+Math.max(0,total-settled).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})};bill.oninput=paid.oninput=update;update()})();</script>@endpush
