@extends('layouts.app')
@section('title','New Expense Bill')
@section('content')
<div class="mb-4"><h1 class="h3 page-title mb-1">{{ $previous?'Continue Expense Bill':'New Expense Bill' }}</h1><p class="text-muted mb-0">Link recurring bills such as electricity, water, rent, internet, or subscriptions to their previous bill.</p></div>
<form method="POST" action="{{ route('expenses.store') }}" id="expense-form">@csrf<div class="card"><div class="card-body p-4"><div class="row g-3">
<div class="col-12"><label class="form-label">Continue from previous bill</label><select id="previous-bill" name="previous_expense_id" class="form-select"><option value="">Start a new bill series</option>@foreach($recentBills as $bill)<option value="{{ $bill->id }}" data-account="{{ $bill->account_id }}" data-payee="{{ $bill->payee }}" data-description="{{ $bill->description }}" data-balance="{{ $bill->balance_amount }}" @selected(old('previous_expense_id',$previous?->id)==$bill->id)>{{ $bill->document_number }} — {{ $bill->payee }}{{ $bill->billing_period?' ('.$bill->billing_period.')':'' }} · Outstanding Rs. {{ number_format($bill->balance_amount,2) }}</option>@endforeach</select><div class="form-text">Selecting a previous bill keeps the history connected. Its unpaid balance remains on that earlier bill and is not added again.</div></div>
<div id="previous-context" class="col-12 {{ $previous?'':'d-none' }}"><div class="alert alert-info mb-0">Previous bill outstanding: <strong>Rs. <span id="previous-balance">{{ number_format($previous?->balance_amount ?? 0,2) }}</span></strong>. It remains payable on the previous bill and is shown separately from this new bill.</div></div>
<div class="col-md-3"><label class="form-label">Bill date</label><input type="date" name="expense_date" value="{{ old('expense_date',now()->toDateString()) }}" class="form-control" required></div><div class="col-md-3"><label class="form-label">Due date</label><input type="date" name="due_date" value="{{ old('due_date') }}" class="form-control"></div><div class="col-md-3"><label class="form-label">Expense account</label><select id="expense-account" name="account_id" class="form-select" required>@foreach($accounts as $account)<option value="{{ $account->id }}" @selected(old('account_id',$previous?->account_id)==$account->id)>{{ $account->code }} — {{ $account->name }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label">Bill amount</label><input id="bill-amount" type="number" step=".01" min=".01" name="amount" value="{{ old('amount') }}" class="form-control" required></div>
<div class="col-md-3"><label class="form-label">Billing period</label><input name="billing_period" value="{{ old('billing_period') }}" class="form-control" placeholder="e.g. August 2026"></div><div class="col-md-3"><label class="form-label">Payee / service provider</label><input id="payee" name="payee" value="{{ old('payee',$previous?->payee) }}" class="form-control" placeholder="e.g. Electricity Board" required></div><div class="col-md-2"><label class="form-label">Amount paid now</label><input id="paid-amount" type="number" step=".01" min="0" name="paid_amount" value="{{ old('paid_amount',0) }}" class="form-control" required></div><div class="col-md-2"><label class="form-label">Payment method</label><select id="payment-method" name="payment_method" class="form-select"><option value="">Not paid yet</option>@foreach(['cash'=>'Cash','bank_transfer'=>'Bank transfer','cheque'=>'Cheque','online_payment'=>'Online payment'] as $value=>$label)<option value="{{ $value }}" @selected(old('payment_method')===$value)>{{ $label }}</option>@endforeach</select></div><div class="col-md-2"><label class="form-label">Reference</label><input name="reference" value="{{ old('reference') }}" class="form-control"></div>
<div class="col-12"><div class="alert alert-info mb-0 d-flex justify-content-between"><span>Outstanding payable after posting</span><strong id="balance-preview">Rs. 0.00</strong></div></div><div class="col-12"><label class="form-label">Description</label><textarea id="description" name="description" class="form-control" required>{{ old('description',$previous?->description) }}</textarea></div><div class="col-12 text-end"><button class="btn btn-primary px-4">Post Expense Bill</button></div>
</div></div></div></form>
@endsection
@push('scripts')<script>(()=>{const bill=document.getElementById('bill-amount'),paid=document.getElementById('paid-amount'),method=document.getElementById('payment-method'),preview=document.getElementById('balance-preview'),previous=document.getElementById('previous-bill'),account=document.getElementById('expense-account'),payee=document.getElementById('payee'),description=document.querySelector('[name="description"]'),context=document.getElementById('previous-context'),previousBalance=document.getElementById('previous-balance');const update=()=>{const total=Number(bill.value||0),settled=Number(paid.value||0);paid.max=total||'';method.required=settled>0;method.disabled=settled<=0;if(settled<=0)method.value='';preview.textContent='Rs. '+Math.max(0,total-settled).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})};previous.addEventListener('change',()=>{const option=previous.selectedOptions[0],linked=Boolean(option.value);context.classList.toggle('d-none',!linked);if(!linked)return;account.value=option.dataset.account;payee.value=option.dataset.payee;description.value=option.dataset.description||'';previousBalance.textContent=Number(option.dataset.balance||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})});bill.oninput=paid.oninput=update;update()})();</script>@endpush
