@once
<style>
.report-sheet{background:#fff;color:#182235;max-width:1120px;margin:0 auto;border:1px solid #dfe5ee;box-shadow:0 10px 30px rgba(15,23,42,.06)}
.report-body{padding:28px 38px 34px}.report-letterhead{display:flex;justify-content:space-between;gap:30px;padding:28px 38px 22px;border-bottom:3px solid #17396b}.report-logo{width:240px;height:64px;object-fit:contain;object-position:left center}.report-company{text-align:right;font-size:.82rem;line-height:1.45;color:#526174}.report-title-band{display:flex;justify-content:space-between;gap:20px;align-items:end;padding:22px 38px;background:#f5f8fc;border-bottom:1px solid #dfe5ee}.report-title-band h1{margin:0;color:#102a50;font-size:1.55rem;font-weight:750;text-transform:uppercase;letter-spacing:.035em}.report-meta{text-align:right;font-size:.8rem;color:#526174}.report-meta strong{color:#182235}.report-sheet table{font-size:.85rem}.report-sheet table thead th{background:#17396b!important;color:#fff!important;border:0;padding:10px}.report-sheet table tbody td,.report-sheet table tbody th{padding:9px 10px;border-color:#e6eaf0}.report-sheet table tfoot th,.report-sheet table tfoot td{padding:10px;border-top:2px solid #17396b}.report-section td,.report-section th{background:#eaf1fa!important;color:#17396b!important;text-transform:uppercase;font-size:.76rem;letter-spacing:.05em}.report-signatures{display:grid;grid-template-columns:repeat(3,1fr);gap:42px;margin-top:70px;padding-top:8px}.signature-box{text-align:center;font-size:.78rem;color:#526174}.signature-line{border-top:1px solid #546274;padding-top:7px;color:#182235;font-weight:600}.report-footer{display:flex;justify-content:space-between;border-top:1px solid #dfe5ee;margin-top:34px;padding-top:12px;font-size:.72rem;color:#6b7280}.report-actions{max-width:1120px;margin:0 auto 18px;display:flex;justify-content:space-between;align-items:center}.report-money{font-variant-numeric:tabular-nums}.report-status{font-weight:700}.report-confidential{font-size:.7rem;text-transform:uppercase;letter-spacing:.08em;color:#9a3412}
@page{size:A4 portrait;margin:10mm}
@media print{
html,body{background:#fff!important;margin:0!important;padding:0!important;-webkit-print-color-adjust:exact;print-color-adjust:exact}
*{box-sizing:border-box}.sidebar,.topbar,.no-print,.alert{display:none!important}.main{margin:0!important;min-height:0!important}.content{padding:0!important}
.report-sheet{width:190mm!important;max-width:190mm!important;margin:0 auto!important;border:0!important;box-shadow:none!important;overflow:visible!important}
.report-letterhead{padding:0 0 8mm!important;border-bottom-width:2px}.report-logo{width:58mm;height:15mm}.report-company{font-size:7.5pt}.report-title-band{padding:5mm 0!important;background:#f5f8fc!important}.report-title-band h1{font-size:15pt}.report-meta{font-size:7.5pt}
.report-body{padding:5mm 0 0!important}.report-sheet table{width:100%!important;font-size:8pt!important;table-layout:auto}.report-sheet table thead{display:table-header-group}.report-sheet table tfoot{display:table-row-group}.report-sheet table tr{break-inside:avoid;page-break-inside:avoid}.report-sheet table th,.report-sheet table td{padding:2.1mm 1.8mm!important}.report-sheet a{color:inherit!important;text-decoration:none!important}
.report-signatures{break-inside:avoid;page-break-inside:avoid;margin-top:12mm!important;gap:10mm}.signature-box{font-size:7pt}.report-footer{break-inside:avoid;page-break-inside:avoid;position:static!important;margin-top:6mm!important;padding-top:3mm!important;font-size:6.5pt}
}
</style>
@endonce
