@extends('layouts.app')
@section('title','Customer Details - '.$customer->name)
@section('content')
@include('reports.partials.professional-header',['reportTitle'=>'Customer Account Profile','reportPeriod'=>$customer->name.' · Customer code '.$customer->code,'reportReference'=>'CUSTOMER-'.$customer->code.'-'.now()->format('Ymd'),'backUrl'=>route('customers.show',$customer)])
<style>
.customer-profile-grid{display:grid;grid-template-columns:1.15fr .85fr;gap:18px;margin-bottom:18px}.customer-panel{border:1px solid #dfe5ee;border-radius:8px;padding:16px}.customer-panel h2,.customer-section-title{font-size:.9rem;color:#17396b;text-transform:uppercase;letter-spacing:.05em}.customer-panel h2{border-bottom:1px solid #dfe5ee;padding-bottom:8px;margin-bottom:12px}.customer-details{display:grid;grid-template-columns:115px 1fr;gap:7px 12px;margin:0}.customer-details dt{font-weight:700}.customer-details dd{margin:0}.customer-summary{display:grid;grid-template-columns:1fr 1fr;gap:10px}.customer-summary>div{background:#f5f8fc;border-radius:7px;padding:11px}.customer-summary span{display:block;color:#667085;font-size:.75rem}.customer-summary strong{font-size:1rem;color:#102a50}.customer-summary .due strong{color:#dc3545}.customer-section-title{margin:18px 0 8px}
@media print{.customer-profile-grid{gap:4mm;margin-bottom:4mm}.customer-panel{padding:3mm;border-radius:1mm}.customer-panel h2{font-size:8pt;padding-bottom:1.5mm;margin-bottom:2mm}.customer-details{grid-template-columns:28mm 1fr;gap:1.2mm 2mm;font-size:8pt}.customer-summary{gap:2mm}.customer-summary>div{padding:2mm}.customer-summary span{font-size:6.5pt}.customer-summary strong{font-size:8.5pt}.customer-section-title{font-size:8pt;margin:3mm 0 1.5mm}.report-body{padding-top:3mm!important}.report-signatures{margin-top:7mm!important}}
</style>
<div class="customer-profile-grid">
<section class="customer-panel"><h2>Customer Information</h2><dl class="customer-details"><dt>Customer name</dt><dd>{{ $customer->name }}</dd><dt>Business</dt><dd>{{ $customer->business_name ?: '—' }}</dd><dt>Customer code</dt><dd>{{ $customer->code }}</dd><dt>Telephone</dt><dd>{{ $customer->phone ?: '—' }}</dd><dt>Email</dt><dd>{{ $customer->email ?: '—' }}</dd><dt>Billing address</dt><dd>{{ $customer->billing_address ?: '—' }}</dd></dl></section>
<section class="customer-panel"><h2>Credit Position</h2><div class="customer-summary"><div><span>Total credit invoiced</span><strong>Rs. {{ number_format((float)$summary->total_invoiced,2) }}</strong></div><div><span>Total paid</span><strong>Rs. {{ number_format((float)$summary->total_received,2) }}</strong></div><div class="due"><span>Current receivable</span><strong>Rs. {{ number_format((float)$summary->current_receivable,2) }}</strong></div><div><span>Credit terms</span><strong>{{ $customer->credit_enabled ? (($customer->default_credit_days ?? 0).' days') : 'Disabled' }}</strong></div></div></section>
</div>
<h2 class="customer-section-title">Recent Posted Invoices</h2><div class="table-responsive"><table class="table table-sm align-middle mb-0"><thead><tr><th>Date</th><th>Invoice</th><th>Sale type</th><th class="text-end">Invoice total</th><th class="text-end">Paid</th><th class="text-end">Receivable</th></tr></thead><tbody>@forelse($sales as $sale)<tr><td>{{ $sale->sale_date->format('d M Y') }}</td><td>{{ $sale->document_number }}</td><td>{{ ucfirst($sale->channel) }} {{ ucfirst($sale->payment_type) }}</td><td class="text-end">{{ number_format($sale->grand_total,2) }}</td><td class="text-end">{{ number_format($sale->paid_amount,2) }}</td><td class="text-end">{{ number_format($sale->balance_amount,2) }}</td></tr>@empty<tr><td colspan="6" class="text-center text-muted">No posted invoices.</td></tr>@endforelse</tbody></table></div>
<h2 class="customer-section-title">Recent Payments Received</h2><div class="table-responsive"><table class="table table-sm align-middle mb-0"><thead><tr><th>Date</th><th>Receipt</th><th>Payment method</th><th class="text-end">Amount received</th><th class="text-end">Applied to invoices</th></tr></thead><tbody>@forelse($receipts as $receipt)<tr><td>{{ $receipt->receipt_date->format('d M Y') }}</td><td>{{ $receipt->receipt_number }}</td><td>{{ str($receipt->payment_method)->headline() }}</td><td class="text-end">{{ number_format($receipt->amount,2) }}</td><td class="text-end">{{ number_format($receipt->allocated_amount,2) }}</td></tr>@empty<tr><td colspan="5" class="text-center text-muted">No payments received.</td></tr>@endforelse</tbody></table></div>
<p class="small text-muted mt-3 mb-0">This profile summarizes the customer account as at {{ now()->format('d F Y, H:i') }}. Refer to the full customer ledger for complete transaction history.</p>
@include('reports.partials.professional-footer')
@endsection
