@extends('layouts.app')
@section('title',$customer->name)
@section('content')
<div class="d-flex justify-content-between align-items-start mb-4"><div><a href="{{ route('customers.index') }}" class="text-decoration-none">&larr; Customers</a><h1 class="h3 page-title mt-2 mb-1">{{ $customer->name }}</h1><p class="text-muted mb-0">Customer profile and complete account position · {{ $customer->code }}</p></div><div class="d-flex gap-2 flex-wrap justify-content-end"><a href="{{ route('customers.print',$customer) }}" class="btn btn-outline-primary"><i class="bi bi-printer"></i> Print Details</a><a href="{{ route('receivables.create',['customer_id'=>$customer->id]) }}" class="btn btn-primary"><i class="bi bi-cash-coin"></i> Receive Payment</a><a href="{{ route('customers.edit',$customer) }}" class="btn btn-outline-secondary"><i class="bi bi-pencil"></i> Edit Profile</a></div></div>
<div class="row g-3 mb-4"><div class="col-md-3"><div class="card card-body"><span class="text-muted">Credit invoiced</span><strong class="fs-4">Rs. {{ number_format((float)$summary->total_invoiced,2) }}</strong></div></div><div class="col-md-3"><div class="card card-body border-start border-success border-4"><span class="text-muted">Paid amount</span><strong class="fs-4 text-success">Rs. {{ number_format((float)$summary->total_received,2) }}</strong></div></div><div class="col-md-3"><div class="card card-body border-start border-danger border-4"><span class="text-muted">Current receivable</span><strong class="fs-4 text-danger">Rs. {{ number_format((float)$summary->current_receivable,2) }}</strong></div></div><div class="col-md-3"><div class="card card-body"><span class="text-muted">Credit status</span><strong class="fs-4">{{ $customer->credit_enabled?'Enabled':'Disabled' }}</strong><small class="text-muted">{{ $customer->default_credit_days??0 }} credit days</small></div></div></div>
<div class="row g-3 mb-4"><div class="col-lg-5"><div class="card h-100"><div class="card-body"><div class="d-flex justify-content-between"><h2 class="h5">Customer details</h2><a href="{{ route('receivables.ledger',$customer) }}">View Full Ledger</a></div><dl class="row mb-0 mt-3"><dt class="col-4">Business</dt><dd class="col-8">{{ $customer->business_name?:'—' }}</dd><dt class="col-4">Phone</dt><dd class="col-8">{{ $customer->phone?:'—' }}</dd><dt class="col-4">Email</dt><dd class="col-8">{{ $customer->email?:'—' }}</dd><dt class="col-4">Address</dt><dd class="col-8">{{ $customer->billing_address?:'—' }}</dd></dl></div></div></div><div class="col-lg-7"><div class="card h-100"><div class="card-body"><h2 class="h5">Related activity</h2><div class="row g-3 mt-1">@foreach(['quotations'=>'Quotations','orders'=>'Sales Orders','deliveries'=>'Deliveries','returns'=>'Returns'] as $key=>$label)<div class="col-6"><div class="border rounded p-3"><div class="text-muted">{{ $label }}</div><strong class="fs-4">{{ $activity[$key] }}</strong></div></div>@endforeach</div></div></div></div></div>
<div class="card mb-4"><div class="card-header bg-white py-3 d-flex justify-content-between"><strong>Recent invoices</strong><a href="{{ route('sales.index',['search'=>$customer->name]) }}">View All Sales</a></div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Date</th><th>Invoice</th><th>Type</th><th>Total</th><th>Paid</th><th>Receivable</th><th></th></tr></thead><tbody>@forelse($sales as $sale)<tr><td>{{ $sale->sale_date->format('d M Y') }}</td><td>{{ $sale->document_number }}</td><td>{{ ucfirst($sale->channel) }} {{ ucfirst($sale->payment_type) }}</td><td>Rs. {{ number_format($sale->grand_total,2) }}</td><td class="text-success">Rs. {{ number_format($sale->paid_amount,2) }}</td><td class="text-danger">Rs. {{ number_format($sale->balance_amount,2) }}</td><td><a href="{{ route('sales.show',$sale) }}">Open</a></td></tr>@empty<tr><td colspan="7" class="text-center text-muted py-4">No invoices.</td></tr>@endforelse</tbody></table></div></div>
<div class="card"><div class="card-header bg-white py-3"><strong>Recent payments received</strong></div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Date</th><th>Receipt</th><th>Method</th><th>Amount</th><th></th></tr></thead><tbody>@forelse($receipts as $receipt)<tr><td>{{ $receipt->receipt_date->format('d M Y') }}</td><td>{{ $receipt->receipt_number }}</td><td>{{ str($receipt->payment_method)->headline() }}</td><td class="text-success">Rs. {{ number_format($receipt->amount,2) }}</td><td><a href="{{ route('receivables.show',$receipt) }}">Open</a></td></tr>@empty<tr><td colspan="5" class="text-center text-muted py-4">No payments received.</td></tr>@endforelse</tbody></table></div></div>
@endsection
