@extends('layouts.app') @section('title','Customer Receipts') @section('content')
<div class="d-flex justify-content-between align-items-center mb-4"><div><h1 class="h3 page-title mb-1">Customer Receivables</h1><p class="text-muted mb-0">Credit invoices, customer ledgers, payments and outstanding balances.</p></div><div class="d-flex gap-2 flex-wrap"><a href="{{ route('receivables.export.excel',request()->only('customer_id')) }}" class="btn btn-outline-success"><i class="bi bi-file-earmark-excel me-1"></i> Excel</a><a href="{{ route('receivables.export.pdf',request()->only('customer_id')) }}" target="_blank" class="btn btn-outline-danger"><i class="bi bi-file-earmark-pdf me-1"></i> PDF Report</a><a href="{{ route('sales.index',['payment_type'=>'credit']) }}" class="btn btn-outline-primary"><i class="bi bi-receipt-cutoff me-1"></i> Credit Sales</a><a href="{{ route('receivables.aging') }}" class="btn btn-outline-primary">Aging Report</a><a href="{{ route('receivables.create') }}" class="btn btn-primary"><i class="bi bi-plus-lg"></i> New Receipt</a></div></div>
<div class="row g-3 mb-4">
    <div class="col-md-4"><div class="card h-100"><div class="card-body"><div class="text-muted mb-1">Total credit sales</div><div class="h3 mb-0">Rs. {{ number_format($reportTotals['invoiced'],2) }}</div></div></div></div>
    <div class="col-md-4"><div class="card h-100 border-start border-success border-4"><div class="card-body"><div class="text-muted mb-1">Total paid by customers</div><div class="h3 mb-0 text-success">Rs. {{ number_format($reportTotals['received'],2) }}</div></div></div></div>
    <div class="col-md-4"><div class="card h-100 border-start border-danger border-4"><div class="card-body"><div class="text-muted mb-1">Current receivable</div><div class="h3 mb-0 text-danger">Rs. {{ number_format($reportTotals['current_receivable'],2) }}</div><small class="text-muted">Invoices Rs. {{ number_format($reportTotals['outstanding'],2) }} less paid-not-allocated Rs. {{ number_format($reportTotals['advances'],2) }}</small></div></div></div>
</div>
<div class="card mb-4"><div class="card-header bg-white p-3"><div class="fw-semibold">Customer account summary</div><small class="text-muted">Current receivable is invoice outstanding less payments not yet allocated to an invoice.</small></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th class="ps-4">Customer</th><th>Code</th><th class="text-end">Total invoiced</th><th class="text-end">Paid amount</th><th class="text-end">Invoice outstanding</th><th class="text-end">Paid - not allocated</th><th class="text-end">Current receivable</th><th class="text-end pe-4">Action</th></tr></thead><tbody>@forelse($customers as $customer)<tr><td class="ps-4 fw-semibold">{{ $customer->name }}</td><td>{{ $customer->code }}</td><td class="text-end">Rs. {{ number_format((float)$customer->total_invoiced,2) }}</td><td class="text-end">Rs. {{ number_format((float)$customer->total_received,2) }}</td><td class="text-end">Rs. {{ number_format((float)$customer->outstanding_balance,2) }}</td><td class="text-end text-success">Rs. {{ number_format((float)$customer->available_advance,2) }}</td><td class="text-end fw-semibold {{ (float)$customer->current_receivable>0?'text-danger':'' }}">Rs. {{ number_format((float)$customer->current_receivable,2) }}</td><td class="text-end pe-4"><a class="btn btn-sm btn-outline-primary" href="{{ route('receivables.ledger',$customer) }}"><i class="bi bi-journal-text me-1"></i> View Ledger</a></td></tr>@empty<tr><td colspan="8" class="text-center text-muted py-4">No customers available.</td></tr>@endforelse</tbody></table></div></div>
<h2 class="h5 mb-3">Receipt history</h2>
<div class="card"><div class="card-body"><form class="row g-2 mb-3"><div class="col-md-5"><select name="customer_id" class="form-select"><option value="">All customers</option>@foreach($allCustomers as $c)<option value="{{ $c->id }}" @selected(request('customer_id')==$c->id)>{{ $c->name }}</option>@endforeach</select></div><div class="col"><button class="btn btn-outline-secondary">Filter</button></div></form><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Receipt</th><th>Date</th><th>Customer</th><th>Method</th><th class="text-end">Paid amount</th><th class="text-end">Paid - not allocated</th></tr></thead><tbody>@forelse($receipts as $x)<tr><td><a href="{{ route('receivables.show',$x) }}">{{ $x->receipt_number }}</a></td><td>{{ $x->receipt_date->format('d M Y') }}</td><td>{{ $x->customer->name }}</td><td>{{ str($x->payment_method)->headline() }}</td><td class="text-end">{{ number_format($x->amount,2) }}</td><td class="text-end">{{ number_format($x->unapplied_amount,2) }}</td></tr>@empty<tr><td colspan="6" class="text-center text-muted py-5">No customer receipts recorded.</td></tr>@endforelse</tbody></table></div>{{ $receipts->links() }}</div></div>
@endsection
