<?php
namespace App\Http\Controllers;
use App\Http\Requests\PartyRequest;use Illuminate\Http\Request;
abstract class PartyController extends Controller
{
 protected string $model;protected string $route;protected string $title;
 public function index(Request $r){$q=($this->model)::where('company_id',$r->user()->company_id);if($this->route==='customers')$q->registered();if($s=trim((string)$r->query('search')))$q->where(fn($x)=>$x->where('code','like',"%$s%")->orWhere('name','like',"%$s%")->orWhere('phone','like',"%$s%"));return view('parties.index',['records'=>$q->latest()->paginate(15)->withQueryString(),'route'=>$this->route,'title'=>$this->title]);}
 public function create(Request $r){$allowed=$this->route==='customers'?[route('sales.create'),route('sales.cash.create'),route('sales.credit.create')]:[];$returnTo=in_array($r->query('return_to'),$allowed,true)?$r->query('return_to'):null;return view('parties.form',['record'=>new $this->model,'route'=>$this->route,'title'=>$this->title,'returnTo'=>$returnTo]);}
 public function store(PartyRequest $r){$d=$this->data($r);$d['company_id']=$r->user()->company_id;if($this->route==='customers'){$d['customer_type_id']=$this->customerType($r);$d['billing_address']=$d['address']??null;unset($d['address']);}$record=($this->model)::create($d);$allowed=$this->route==='customers'?[route('sales.create'),route('sales.cash.create'),route('sales.credit.create')]:[];if(in_array($r->input('return_to'),$allowed,true))return redirect()->to($r->input('return_to').'?customer_id='.$record->id)->with('success','Customer created and selected for this sale.');return redirect()->route($this->route.'.index')->with('success',$this->title.' created successfully.');}
 public function edit($record){$query=($this->model)::where('company_id',auth()->user()->company_id);if($this->route==='customers')$query->registered();$record=$query->findOrFail($record);return view('parties.form',compact('record')+['route'=>$this->route,'title'=>$this->title,'returnTo'=>null]);}
 public function update(PartyRequest $r,$record){$query=($this->model)::where('company_id',$r->user()->company_id);if($this->route==='customers')$query->registered();$record=$query->findOrFail($record);$d=$this->data($r);if($this->route==='customers'){$d['billing_address']=$d['address']??null;unset($d['address']);}$record->update($d);return redirect()->route($this->route.'.index')->with('success',$this->title.' updated successfully.');}
 protected function data($r){$fields=$this->route==='customers'?['code','name','business_name','phone','email','address','credit_enabled','default_due_term','default_credit_days','is_active']:['code','name','contact_person','phone','email','address','is_active'];$d=$r->safe()->only($fields);$d['is_active']=$r->boolean('is_active');if($this->route==='customers')$d['credit_enabled']=$r->boolean('credit_enabled');return $d;}
 protected function customerType($r){return \Illuminate\Support\Facades\DB::table('customer_types')->where('company_id',$r->user()->company_id)->where('code',$r->input('customer_type','RET'))->value('id');}
}
