@extends('layouts.app')
@section('title','Add Products')
@push('styles')
<style>
.product-sheet th:nth-child(15) .required-mark{display:none}
.product-sheet-card{overflow:hidden}.sheet-toolbar{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:14px 16px;background:#fff;border-bottom:1px solid var(--line)}.sheet-wrap{overflow:auto;max-height:calc(100vh - 350px);min-height:390px;background:#fff}.product-sheet{width:max-content;min-width:100%;border-collapse:separate;border-spacing:0;font-size:.86rem}.product-sheet th,.product-sheet td{border-right:1px solid #d7e0ea;border-bottom:1px solid #d7e0ea;padding:0}.product-sheet th{position:sticky;top:0;z-index:3;height:42px;padding:7px 9px;background:#e8eef5;color:#42526a;font-size:.7rem;text-transform:uppercase;letter-spacing:.035em;white-space:nowrap}.product-sheet .row-number{position:sticky;left:0;z-index:2;width:46px;min-width:46px;text-align:center;background:#f0f4f8;color:#64748b;font-weight:700}.product-sheet th.row-number{z-index:5}.sheet-cell{width:100%;height:40px;padding:7px 9px;border:0;border-radius:0;background:transparent;color:#172033;outline:0}.sheet-cell:focus{background:#fff;box-shadow:inset 0 0 0 2px #2563eb}.product-sheet select.sheet-cell{padding-right:27px}.col-code{width:125px}.col-barcode{width:155px}.col-name{width:230px}.col-select{width:165px}.col-small{width:115px}.col-model{width:140px}.col-location{width:125px}.col-toggle{width:88px;text-align:center}.row-actions{width:52px;text-align:center}.sheet-check{width:18px;height:18px;margin:0;vertical-align:middle}.required-mark{color:#dc3545}.sheet-help{color:#64748b;font-size:.82rem}.sheet-footer{position:sticky;bottom:0;display:flex;align-items:center;justify-content:space-between;gap:12px;padding:14px 16px;background:#f8fafc;border-top:1px solid var(--line)}.cell-error{background:#fff1f2!important}.paste-toast{position:fixed;right:24px;bottom:24px;z-index:1080}@media(max-width:991px){.sheet-wrap{max-height:none}.sheet-toolbar,.sheet-footer{align-items:flex-start;flex-direction:column}}
</style>
@endpush
@section('content')
<div class="mb-4 d-flex align-items-start justify-content-between gap-3"><div><a href="{{ route('products.index') }}" class="text-decoration-none"><i class="bi bi-arrow-left"></i> Back to products</a><h1 class="h3 page-title mt-2 mb-1">Add Products</h1><p class="text-muted mb-0">Enter products in rows, just like an Excel sheet.</p></div><span class="badge text-bg-primary fs-6"><span id="row-count">1</span> row</span></div>
<form method="POST" action="{{ route('products.store') }}" id="product-sheet-form">@csrf
<div class="card product-sheet-card">
 <div class="sheet-toolbar"><div><strong>Manual product sheet</strong><div class="sheet-help"><i class="bi bi-clipboard me-1"></i>Copy cells from Excel and paste into the first matching cell. Use Tab or arrow keys to move.</div></div><button class="btn btn-outline-primary btn-sm" type="button" id="add-row"><i class="bi bi-plus-lg me-1"></i>Add row</button></div>
 <div class="sheet-wrap"><table class="product-sheet" id="product-sheet"><thead><tr><th class="row-number">#</th><th class="col-code">Item code <span class="required-mark">*</span></th><th class="col-barcode">Barcode</th><th class="col-name">Product name <span class="required-mark">*</span></th><th class="col-select">Category <span class="required-mark">*</span></th><th class="col-select">Brand</th><th class="col-select">Unit <span class="required-mark">*</span></th><th class="col-model">Model</th><th class="col-small">Cost price <span class="required-mark">*</span></th><th class="col-small">Retail price <span class="required-mark">*</span></th><th class="col-small">Wholesale <span class="required-mark">*</span></th><th class="col-small">Min stock <span class="required-mark">*</span></th><th class="col-small">Reorder level <span class="required-mark">*</span></th><th class="col-location">Rack location</th><th class="col-small">Warranty months <span class="required-mark">*</span></th><th class="col-toggle">Serial</th><th class="col-toggle">Active</th><th class="row-actions"></th></tr></thead><tbody></tbody></table></div>
 <div class="sheet-footer"><div class="sheet-help"><span class="required-mark">*</span> Required columns · Up to 100 products per save</div><div class="d-flex flex-wrap gap-2"><a class="btn btn-light" href="{{ route('products.index') }}">Cancel</a><button class="btn btn-outline-primary px-3" type="submit" name="after_save" value="purchase"><i class="bi bi-bag-plus me-1"></i>Save & add to purchase</button><button class="btn btn-primary px-4" type="submit"><i class="bi bi-check2-circle me-1"></i>Save products</button></div></div>
</div></form>
<template id="product-row-template"><tr><td class="row-number"></td><td><input class="sheet-cell" data-field="item_code" maxlength="60" required></td><td><input class="sheet-cell" data-field="barcode" maxlength="100"></td><td><input class="sheet-cell" data-field="name" maxlength="180" required></td><td><select class="sheet-cell" data-field="product_category_id" required><option value="">Select category</option>@foreach($categories as $x)<option value="{{ $x->id }}">{{ $x->name }}</option>@endforeach</select></td><td><select class="sheet-cell" data-field="brand_id"><option value="">None</option>@foreach($brands as $x)<option value="{{ $x->id }}">{{ $x->name }}</option>@endforeach</select></td><td><select class="sheet-cell" data-field="unit_id" required><option value="">Select unit</option>@foreach($units as $x)<option value="{{ $x->id }}" @selected($x->code==='PCS')>{{ $x->name }}</option>@endforeach</select></td><td><input class="sheet-cell" data-field="model" maxlength="100"></td><td><input class="sheet-cell" data-field="average_cost" type="number" min="0" step="0.0001" value="0" required></td><td><input class="sheet-cell" data-field="retail_price" type="number" min="0" step="0.01" value="0" required></td><td><input class="sheet-cell" data-field="wholesale_price" type="number" min="0" step="0.01" value="0" required></td><td><input class="sheet-cell" data-field="minimum_stock" type="number" min="0" step="0.0001" value="0" required></td><td><input class="sheet-cell" data-field="reorder_level" type="number" min="0" step="0.0001" value="0" required></td><td><input class="sheet-cell" data-field="rack_location" maxlength="80"></td><td><input class="sheet-cell" data-field="warranty_months" type="number" min="0" max="120" step="1" value="0" required></td><td class="text-center"><input class="form-check-input sheet-check" data-field="serial_tracking" type="checkbox" value="1"></td><td class="text-center"><input class="form-check-input sheet-check" data-field="is_active" type="checkbox" value="1" checked></td><td class="text-center"><button class="btn btn-sm btn-link text-danger remove-row" type="button" title="Remove row"><i class="bi bi-trash"></i></button></td></tr></template>
<div class="modal fade" id="new-category-modal" tabindex="-1" aria-hidden="true"><div class="modal-dialog"><div class="modal-content"><form id="new-category-form"><div class="modal-header"><h2 class="modal-title fs-5">Create new category</h2><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div id="category-errors" class="alert alert-danger d-none"></div><div class="mb-3"><label class="form-label">Category code</label><input name="code" class="form-control" maxlength="50" required placeholder="e.g. ELEC"></div><div><label class="form-label">Category name</label><input name="name" class="form-control" maxlength="120" required placeholder="e.g. Electronics"></div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Cancel</button><button type="submit" class="btn btn-primary">Create category</button></div></form></div></div></div>
@endsection
@push('scripts')
<script>
(()=>{const body=document.querySelector('#product-sheet tbody'),template=document.getElementById('product-row-template'),count=document.getElementById('row-count'),old=@json(old('items', [])),categoryModalElement=document.getElementById('new-category-modal'),categoryModal=new bootstrap.Modal(categoryModalElement),categoryForm=document.getElementById('new-category-form'),categoryErrors=document.getElementById('category-errors');let next=0,activeCategorySelect=null;
const warrantyTemplate=template.content.querySelector('[data-field="warranty_months"]');warrantyTemplate.removeAttribute('required');warrantyTemplate.value='';warrantyTemplate.placeholder='Optional';
const refresh=()=>{[...body.rows].forEach((row,i)=>{row.querySelector('.row-number').textContent=i+1;row.querySelectorAll('[data-field]').forEach(el=>el.name=`items[${i}][${el.dataset.field}]`)});count.textContent=body.rows.length;count.parentElement.lastChild.textContent=body.rows.length===1?' row':' rows'};
const add=(values={})=>{if(body.rows.length>=100)return;const row=template.content.firstElementChild.cloneNode(true),category=row.querySelector('[data-field="product_category_id"]');category.add(new Option('＋ Create new category','__new__'));row.querySelectorAll('[data-field]').forEach(el=>{const v=values[el.dataset.field];if(v!==undefined){if(el.type==='checkbox')el.checked=String(v)==='1'||v===true;else el.value=v}});row.querySelector('.remove-row').onclick=()=>{if(body.rows.length===1){row.querySelectorAll('input').forEach(x=>{if(x.type==='checkbox')x.checked=x.dataset.field==='is_active';else if(x.type==='number')x.value=0;else x.value=''})}else row.remove();refresh()};body.append(row);next++;refresh();return row};
(old.length?old:[{}]).forEach(add);document.getElementById('add-row').onclick=()=>add().querySelector('[data-field="item_code"]').focus();
body.addEventListener('keydown',e=>{const cell=e.target.closest('[data-field]');if(!cell)return;const cells=[...body.querySelectorAll('[data-field]')],i=cells.indexOf(cell),cols=17;if(e.key==='Enter'){e.preventDefault();(cells[i+1]||add().querySelector('[data-field="item_code"]')).focus()}else if(e.key==='ArrowDown'&&i+cols<cells.length){e.preventDefault();cells[i+cols].focus()}else if(e.key==='ArrowUp'&&i-cols>=0){e.preventDefault();cells[i-cols].focus()}});
body.addEventListener('paste',e=>{const start=e.target.closest('[data-field]');if(!start)return;const text=e.clipboardData.getData('text/plain');if(!text.includes('\t')&&!text.includes('\n'))return;e.preventDefault();const matrix=text.replace(/\r/g,'').split('\n').filter((r,i,a)=>r!==''||i<a.length-1).map(r=>r.split('\t')),rows=[...body.rows],startRow=rows.indexOf(start.closest('tr')),startCol=[...start.closest('tr').querySelectorAll('[data-field]')].indexOf(start);while(body.rows.length<startRow+matrix.length&&body.rows.length<100)add();matrix.forEach((values,r)=>{const cells=[...body.rows[startRow+r].querySelectorAll('[data-field]')];values.forEach((value,c)=>{const el=cells[startCol+c];if(!el)return;if(el.tagName==='SELECT'){const option=[...el.options].find(o=>o.text.trim().toLowerCase()===value.trim().toLowerCase()||o.value===value.trim());if(option)el.value=option.value}else if(el.type==='checkbox')el.checked=/^(1|yes|true|active)$/i.test(value.trim());else el.value=value.trim()})});refresh()});
body.addEventListener('change',e=>{if(e.target.dataset.field!=='product_category_id'||e.target.value!=='__new__')return;activeCategorySelect=e.target;e.target.value='';categoryErrors.classList.add('d-none');categoryForm.reset();categoryModal.show();setTimeout(()=>categoryForm.elements.code.focus(),200)});
categoryForm.addEventListener('submit',async e=>{e.preventDefault();const button=categoryForm.querySelector('[type="submit"]');button.disabled=true;categoryErrors.classList.add('d-none');try{const response=await fetch(@json(route('categories.quick-store')),{method:'POST',headers:{'Accept':'application/json','X-CSRF-TOKEN':@json(csrf_token())},body:new FormData(categoryForm)}),data=await response.json();if(!response.ok)throw data;body.querySelectorAll('[data-field="product_category_id"]').forEach(select=>{const createOption=[...select.options].find(option=>option.value==='__new__'),option=new Option(data.name,data.id);select.add(option,createOption);if(select===activeCategorySelect)select.value=String(data.id)});categoryModal.hide()}catch(error){const messages=error.errors?Object.values(error.errors).flat():['Unable to create category.'];categoryErrors.textContent=messages.join(' ');categoryErrors.classList.remove('d-none')}finally{button.disabled=false}});
document.getElementById('product-sheet-form').addEventListener('submit',()=>body.querySelectorAll('[data-field]').forEach(el=>el.classList.toggle('cell-error',!el.checkValidity())));
})();
</script>
@endpush
