@extends('layouts.app')
@section('title',$saleMode==='credit'?'New Credit Sale':'Cash Sale / POS')
@push('styles')<style>.pos-grid{display:grid;grid-template-columns:minmax(0,1fr) 390px;gap:20px}.pos-total{font-size:2rem;font-weight:800}.product-search{font-size:1.1rem;padding:.85rem 2.8rem .85rem .95rem}.product-search-wrap{position:relative}.product-search-icon{position:absolute;right:1rem;top:50%;transform:translateY(-50%);color:#6b7280;pointer-events:none}.category-strip{display:flex;gap:8px;overflow-x:auto;padding:12px 0 2px;scrollbar-width:thin}.category-button{white-space:nowrap;border:1px solid #dce3ec;background:#fff;color:#334155;border-radius:999px;padding:7px 13px;font-weight:600}.category-button:hover,.category-button.active{border-color:#2563eb;background:#2563eb;color:#fff}.product-results{position:absolute;z-index:30;top:calc(100% + 5px);left:0;right:0;max-height:330px;overflow:auto;background:#fff;border:1px solid #dce3ec;border-radius:10px;box-shadow:0 14px 30px rgba(15,31,56,.16)}.product-result{display:flex;justify-content:space-between;gap:16px;width:100%;padding:11px 14px;border:0;border-bottom:1px solid #edf0f4;background:#fff;text-align:left}.product-result:last-child{border-bottom:0}.product-result:hover,.product-result.active{background:#eaf1ff}.product-result:disabled{background:#f8fafc;color:#9ca3af}.cart-table td{vertical-align:middle}.channel-choice{display:grid;grid-template-columns:1fr 1fr;gap:8px}.channel-choice input{position:absolute;opacity:0}.channel-choice label{display:block;border:2px solid #dce3ec;border-radius:9px;padding:10px;text-align:center;cursor:pointer;font-weight:700}.channel-choice input:checked+label{border-color:#2563eb;background:#eaf1ff;color:#174db5}.sale-mode-banner{border-left:4px solid #2563eb}@media(max-width:1100px){.pos-grid{grid-template-columns:1fr}}</style>@endpush
@section('content')
@php($backdated=$backdated??false)
@php($walkIn=$customers->firstWhere('code','WALK-IN'))
@php($categories=$products->pluck('category')->filter()->unique('id')->sortBy('name'))
<form method="POST" action="{{ $backdated?route('backdated-invoices.store'):route('sales.store') }}" id="pos-form">@csrf<input type="hidden" name="payment_type" value="{{ $saleMode }}"><input type="hidden" name="paid_amount" id="paid" value="0">
<div class="d-flex justify-content-between align-items-start mb-3"><div><h1 class="h3 page-title mb-1">{{ $backdated?'Backdated '.($saleMode==='credit'?'Credit Invoice':'Cash Sale'):($saleMode==='credit'?'New Credit Sale':'Cash Sale / POS') }}</h1><p class="text-muted mb-0">{{ $saleMode==='credit'?'Invoice a registered credit customer for payment later.':'Fast checkout for walk-in or registered retail customers.' }}</p></div><div class="d-flex gap-2"><a href="{{ $backdated?route('backdated-invoices.create',['type'=>$saleMode==='credit'?'cash':'credit']):($saleMode==='credit'?route('sales.cash.create'):route('sales.credit.create')) }}" class="btn btn-outline-primary">{{ $saleMode==='credit'?($backdated?'Backdated Cash Sale':'Open Cash POS'):($backdated?'Backdated Credit Sale':'New Credit Sale') }}</a><a href="{{ $backdated?route('backdated-invoices.index'):route('sales.index') }}" class="btn btn-light">{{ $backdated?'Requests':'Invoice History' }}</a></div></div>
<div class="alert {{ $saleMode==='credit'?'alert-warning':'alert-info' }} sale-mode-banner py-2"><strong>{{ $saleMode==='credit'?'Credit workflow:':'Cash workflow:' }}</strong> {{ $saleMode==='credit'?'registered, credit-enabled customer and due date are required. Payment is recorded later in Receivables.':'Temporary cash customer is selected by default and no customer account is created. Payment must be collected in full.' }}</div>
@if($backdated)<div class="card mb-3"><div class="card-body"><label class="form-label fw-bold">Original invoice date</label><input class="form-control" style="max-width:260px" type="date" name="invoice_date" min="{{ now()->subDays($backdateDays)->toDateString() }}" max="{{ now()->subDay()->toDateString() }}" value="{{ old('invoice_date',now()->subDay()->toDateString()) }}" required><div class="form-text">Allowed window: previous {{ $backdateDays }} days. Nothing is posted until CFO approval.</div></div></div>@endif
<div class="pos-grid"><section><div class="card mb-3"><div class="card-body p-3"><div class="product-search-wrap"><input id="product-search" class="form-control product-search" type="search" placeholder="Search item code, product name or scan barcode" autocomplete="off" aria-label="Search products" aria-controls="product-results"><i class="bi bi-search product-search-icon"></i><div id="product-results" class="product-results d-none" role="listbox"></div></div><div class="category-strip" aria-label="Product categories"><button type="button" class="category-button active" data-category="">All Items</button>@foreach($categories as $category)<button type="button" class="category-button" data-category="{{ $category->id }}">{{ $category->name }}</button>@endforeach</div><select id="product-picker" class="d-none" aria-hidden="true" tabindex="-1"><option value=""></option>@foreach($products as $product)@php($retail=$product->prices->where('price_type','retail')->where('is_active',true)->first()?->amount??0)@php($wholesale=$product->prices->where('price_type','wholesale')->where('is_active',true)->first()?->amount??0)<option value="{{ $product->id }}" data-name="{{ $product->name }}" data-code="{{ $product->item_code }}" data-barcode="{{ $product->barcode }}" data-category="{{ $product->product_category_id }}" data-category-name="{{ $product->category?->name }}" data-stock="{{ (float) $product->current_quantity }}" data-retail="{{ $retail }}" data-wholesale="{{ $wholesale }}" @disabled($product->current_quantity<=0)>{{ $product->item_code }} | {{ $product->name }} | {{ $product->current_quantity<=0?'OUT OF STOCK':'Stock '.$product->current_quantity }}</option>@endforeach</select></div></div><div class="card"><div class="table-responsive"><table class="table cart-table mb-0"><thead><tr><th class="ps-3">Product</th><th style="width:120px">Qty</th><th style="width:150px">Price</th><th style="width:130px">Total</th><th></th></tr></thead><tbody id="cart"><tr id="empty"><td colspan="5" class="text-center py-5 text-muted">Select a product to begin the sale.</td></tr></tbody></table></div></div></section>
<aside><div class="card"><div class="card-body p-4">
<div class="d-flex justify-content-between align-items-center"><label class="form-label">{{ $saleMode==='credit'?'Registered credit customer':'Customer' }}</label>@if($saleMode==='credit')<a href="{{ route('customers.create',['return_to'=>$backdated?route('backdated-invoices.create',['type'=>'credit']):route('sales.credit.create')]) }}" class="btn btn-sm btn-outline-primary"><i class="bi bi-person-plus"></i> Create customer</a>@endif</div>
@if($saleMode==='cash' && $walkIn)<div class="border rounded-3 p-3 mb-3 bg-light"><div class="d-flex align-items-center gap-2"><i class="bi bi-person fs-4"></i><div><strong>Walk-in Cash Sale</strong><div class="small text-muted">No customer registration required</div></div></div></div>@endif
<select class="form-select mb-3" name="customer_id" id="customer" required>@forelse($customers as $customer)<option value="{{ $customer->id }}" data-channel="{{ $customer->code==='WALK-IN'?'retail':($customer->customerType?->price_tier==='wholesale'?'wholesale':'retail') }}" data-walk-in="{{ $customer->code==='WALK-IN'?1:0 }}" @selected(old('customer_id',request('customer_id',$saleMode==='cash'?$walkIn?->id:null))==$customer->id)>{{ $customer->code==='WALK-IN'?'Temporary Cash Customer (no account)':$customer->name }}</option>@empty<option value="">No eligible customers-create one first</option>@endforelse</select>
<div id="walk-in-name-group" class="mb-3 d-none"><label for="walk-in-customer-name" class="form-label">Customer name <span class="text-muted fw-normal">(optional)</span></label><input id="walk-in-customer-name" class="form-control" name="walk_in_customer_name" value="{{ old('walk_in_customer_name') }}" maxlength="150" placeholder="Enter the walk-in customer's name"><div class="form-text">Printed on this invoice only. No customer account will be created.</div></div>
@if($saleMode==='credit' && $customers->isEmpty())<div class="alert alert-danger py-2">No credit-enabled customers exist. Create a customer before continuing.</div>@endif
<label class="form-label">Pricing channel</label><div class="channel-choice mb-3"><div><input type="radio" name="channel" id="channel-retail" value="retail" @checked(old('channel','retail')==='retail')><label for="channel-retail"><i class="bi bi-person me-1"></i> RETAIL</label></div><div><input type="radio" name="channel" id="channel-wholesale" value="wholesale" @checked(old('channel')==='wholesale')><label for="channel-wholesale"><i class="bi bi-boxes me-1"></i> WHOLESALE</label></div></div>
@if($saleMode==='credit')<label class="form-label">Payment due date</label><input class="form-control mb-3" type="date" name="due_date" value="{{ old('due_date',now()->addDays(30)->toDateString()) }}" min="{{ now()->toDateString() }}" required><input type="hidden" name="payment_method" value="">@endif
<hr><div class="d-flex justify-content-between"><span>Subtotal</span><strong id="subtotal">Rs. 0.00</strong></div><label class="form-label mt-3">Discount</label><input class="form-control" name="discount_amount" id="discount" type="number" value="{{ old('discount_amount',0) }}" min="0" step=".01"><div class="d-flex justify-content-between align-items-end mt-3"><span>Grand total</span><span class="pos-total" id="grand">Rs. 0.00</span></div>
@if($saleMode==='cash')<hr><label class="form-label">Payment method</label><select class="form-select mb-3" name="payment_method" id="method">@foreach(['cash'=>'Cash','credit_card'=>'Credit Card','debit_card'=>'Debit Card','qr'=>'QR Payment','cheque'=>'Cheque','bank_transfer'=>'Bank Transfer','mobile_wallet'=>'Mobile Wallet','online_payment'=>'Online Payment'] as $value=>$label)<option value="{{ $value }}" @selected(old('payment_method')===$value)>{{ $label }}</option>@endforeach</select><div id="cheque" class="d-none"><input class="form-control mb-2" name="cheque_number" value="{{ old('cheque_number') }}" placeholder="Cheque number"><input class="form-control mb-2" name="cheque_bank" value="{{ old('cheque_bank') }}" placeholder="Bank"><input class="form-control mb-3" type="date" name="cheque_date" value="{{ old('cheque_date') }}"></div><input class="form-control mb-3" name="payment_reference" value="{{ old('payment_reference') }}" placeholder="Payment reference (optional)">@else<div class="alert alert-info py-2 mt-3 mb-3"><i class="bi bi-info-circle me-1"></i>No payment method is needed now.</div>@endif
<button class="btn {{ $saleMode==='credit'?'btn-primary':'btn-success' }} btn-lg w-100" id="post" @disabled($saleMode==='credit'&&$customers->isEmpty())>{{ $backdated?'Submit for CFO Approval':($saleMode==='credit'?'Post Credit Invoice':'Complete Cash Sale') }}</button>
</div></div></aside></div></form>
@push('scripts')<script>
let rowIndex=0,activeCategory='';const cart=new Map(),picker=document.querySelector('#product-picker'),search=document.querySelector('#product-search'),results=document.querySelector('#product-results'),productOptions=[...picker.options].filter(option=>option.value),cartBody=document.querySelector('#cart'),saleMode=@json($saleMode);const selectedChannel=()=>document.querySelector('input[name="channel"]:checked').value;const money=value=>'Rs. '+Number(value).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});
function totals(){let subtotal=0;cartBody.querySelectorAll('tr[data-id]').forEach(row=>{const line=Number(row.querySelector('.qty').value)*Number(row.querySelector('.price').value);subtotal+=line;row.querySelector('.line').textContent=money(line)});const grand=Math.max(0,subtotal-Number(document.querySelector('#discount').value||0));document.querySelector('#subtotal').textContent=money(subtotal);document.querySelector('#grand').textContent=money(grand);document.querySelector('#paid').value=saleMode==='cash'?grand.toFixed(2):'0'}
function updateChannel(){const channel=selectedChannel();cart.forEach(row=>row.querySelector('.price').value=channel==='retail'?row.dataset.retail:row.dataset.wholesale);totals()}
function addProduct(option){if(cart.has(option.value)){const qty=cart.get(option.value).querySelector('.qty');qty.value=Number(qty.value)+1;totals();return}document.querySelector('#empty')?.remove();const row=document.createElement('tr');row.dataset.id=option.value;row.dataset.retail=option.dataset.retail;row.dataset.wholesale=option.dataset.wholesale;row.innerHTML=`<td class="ps-3"><strong>${option.dataset.name}</strong><div class="small text-muted">${option.dataset.code} - Available ${option.dataset.stock}</div><input type="hidden" name="items[${rowIndex}][product_id]" value="${option.value}"></td><td><input class="form-control qty" name="items[${rowIndex}][quantity]" type="number" min="0.01" max="${option.dataset.stock}" step="any" value="1"></td><td><input class="form-control price" name="items[${rowIndex}][unit_price]" type="number" min="0" step=".01" value="${selectedChannel()==='retail'?option.dataset.retail:option.dataset.wholesale}"></td><td class="line"></td><td><button class="btn btn-light remove" type="button" aria-label="Remove item" title="Remove item"><i class="bi bi-x-lg"></i></button></td>`;row.querySelectorAll('input').forEach(input=>input.oninput=totals);row.querySelector('.remove').onclick=()=>{cart.delete(option.value);row.remove();totals()};cartBody.append(row);cart.set(option.value,row);rowIndex++;totals()}
function matchingProducts(){const term=search.value.trim().toLowerCase();return productOptions.filter(option=>(!activeCategory||option.dataset.category===activeCategory)&&(!term||[option.dataset.code,option.dataset.name,option.dataset.barcode].some(value=>(value||'').toLowerCase().includes(term)))).slice(0,30)}
function showResults(){results.replaceChildren();const matches=matchingProducts();if(!matches.length){const empty=document.createElement('div');empty.className='p-3 text-muted';empty.textContent='No matching products found.';results.append(empty)}else matches.forEach(option=>{const button=document.createElement('button');button.type='button';button.className='product-result';button.disabled=option.disabled;const details=document.createElement('span');const title=document.createElement('strong');title.textContent=option.dataset.name;const meta=document.createElement('small');meta.className='d-block text-muted';meta.textContent=[option.dataset.code,option.dataset.barcode].filter(Boolean).join(' - ');details.append(title,meta);const stock=document.createElement('span');stock.className='text-nowrap small';stock.textContent=option.disabled?'OUT OF STOCK':'Stock '+option.dataset.stock;button.append(details,stock);button.addEventListener('click',()=>selectProduct(option));results.append(button)});results.classList.remove('d-none')}
function selectProduct(option){if(!option||option.disabled)return;addProduct(option);search.value='';results.classList.add('d-none');search.focus()}
search.addEventListener('focus',showResults);search.addEventListener('input',showResults);search.addEventListener('keydown',event=>{if(event.key==='Escape'){results.classList.add('d-none');return}if(event.key==='Enter'){event.preventDefault();const matches=matchingProducts().filter(option=>!option.disabled);const exact=matches.find(option=>[option.dataset.code,option.dataset.barcode].some(value=>(value||'').toLowerCase()===search.value.trim().toLowerCase()));selectProduct(exact||matches[0])}});document.querySelectorAll('.category-button').forEach(button=>button.addEventListener('click',()=>{activeCategory=button.dataset.category;document.querySelectorAll('.category-button').forEach(item=>item.classList.toggle('active',item===button));search.value='';showResults();search.focus()}));document.addEventListener('click',event=>{if(!event.target.closest('.product-search-wrap')&&!event.target.closest('.category-strip'))results.classList.add('d-none')});document.querySelectorAll('input[name="channel"]').forEach(input=>input.onchange=updateChannel);document.querySelector('#customer').onchange=event=>{const option=event.target.selectedOptions[0];if(!option)return;const walkIn=option.dataset.walkIn==='1';document.querySelector('#walk-in-name-group')?.classList.toggle('d-none',!walkIn);if(walkIn){document.querySelector('#channel-retail').checked=true;document.querySelector('#channel-wholesale').disabled=true}else document.querySelector('#channel-wholesale').disabled=false;const desired=option.dataset.channel;document.querySelector('#channel-'+desired).checked=true;updateChannel()};document.querySelector('#discount').oninput=totals;document.querySelector('#method')?.addEventListener('change',event=>document.querySelector('#cheque').classList.toggle('d-none',event.target.value!=='cheque'));document.querySelector('#customer').dispatchEvent(new Event('change'));totals();
</script>@endpush
@endsection
