@extends('layouts.app')
@section('title',$saleMode==='credit'?'New Credit Sale':'Cash Sale / POS')
@push('styles')<style>.pos-grid{display:grid;grid-template-columns:minmax(0,1fr) 390px;gap:20px}.pos-total{font-size:2rem;font-weight:800}.product-search{font-size:1.1rem;padding:.85rem}.cart-table td{vertical-align:middle}.channel-choice{display:grid;grid-template-columns:1fr 1fr;gap:8px}.channel-choice input{position:absolute;opacity:0}.channel-choice label{display:block;border:2px solid #dce3ec;border-radius:9px;padding:10px;text-align:center;cursor:pointer;font-weight:700}.channel-choice input:checked+label{border-color:#2563eb;background:#eaf1ff;color:#174db5}.sale-mode-banner{border-left:4px solid #2563eb}@media(max-width:1100px){.pos-grid{grid-template-columns:1fr}}</style>@endpush
@section('content')
@php($walkIn=$customers->firstWhere('code','WALK-IN'))
<form method="POST" action="{{ route('sales.store') }}" id="pos-form">@csrf<input type="hidden" name="payment_type" value="{{ $saleMode }}"><input type="hidden" name="paid_amount" id="paid" value="0">
<div class="d-flex justify-content-between align-items-start mb-3"><div><h1 class="h3 page-title mb-1">{{ $saleMode==='credit'?'New Credit Sale':'Cash Sale / POS' }}</h1><p class="text-muted mb-0">{{ $saleMode==='credit'?'Invoice a registered credit customer for payment later.':'Fast checkout for walk-in or registered retail customers.' }}</p></div><div class="d-flex gap-2"><a href="{{ $saleMode==='credit'?route('sales.cash.create'):route('sales.credit.create') }}" class="btn btn-outline-primary">{{ $saleMode==='credit'?'Open Cash POS':'New Credit Sale' }}</a><a href="{{ route('sales.index') }}" class="btn btn-light">Invoice History</a></div></div>
<div class="alert {{ $saleMode==='credit'?'alert-warning':'alert-info' }} sale-mode-banner py-2"><strong>{{ $saleMode==='credit'?'Credit workflow:':'Cash workflow:' }}</strong> {{ $saleMode==='credit'?'registered, credit-enabled customer and due date are required. Payment is recorded later in Receivables.':'Walk-in Customer is selected by default. Payment must be collected in full.' }}</div>
<div class="pos-grid"><section><div class="card mb-3"><div class="card-body p-3"><select id="product-picker" class="form-select product-search"><option value="">Search or select product / barcode</option>@foreach($products as $product)@php($retail=$product->prices->where('price_type','retail')->where('is_active',true)->first()?->amount??0)@php($wholesale=$product->prices->where('price_type','wholesale')->where('is_active',true)->first()?->amount??0)<option value="{{ $product->id }}" data-name="{{ $product->name }}" data-code="{{ $product->item_code }}" data-stock="{{ $product->current_quantity }}" data-retail="{{ $retail }}" data-wholesale="{{ $wholesale }}" @disabled($product->current_quantity<=0)>{{ $product->item_code }} | {{ $product->name }} | {{ $product->current_quantity<=0?'OUT OF STOCK':'Stock '.$product->current_quantity }}</option>@endforeach</select></div></div><div class="card"><div class="table-responsive"><table class="table cart-table mb-0"><thead><tr><th class="ps-3">Product</th><th style="width:120px">Qty</th><th style="width:150px">Price</th><th style="width:130px">Total</th><th></th></tr></thead><tbody id="cart"><tr id="empty"><td colspan="5" class="text-center py-5 text-muted">Select a product to begin the sale.</td></tr></tbody></table></div></div></section>
<aside><div class="card"><div class="card-body p-4">
<div class="d-flex justify-content-between align-items-center"><label class="form-label">{{ $saleMode==='credit'?'Registered credit customer':'Customer' }}</label>@if($saleMode==='credit')<a href="{{ route('customers.create',['return_to'=>route('sales.credit.create')]) }}" class="btn btn-sm btn-outline-primary"><i class="bi bi-person-plus"></i> Create customer</a>@endif</div>
@if($saleMode==='cash' && $walkIn)<div class="border rounded-3 p-3 mb-3 bg-light"><div class="d-flex align-items-center gap-2"><i class="bi bi-person fs-4"></i><div><strong>Walk-in Cash Sale</strong><div class="small text-muted">No customer registration required</div></div></div></div>@endif
<select class="form-select mb-3" name="customer_id" id="customer" required>@forelse($customers as $customer)<option value="{{ $customer->id }}" data-channel="{{ $customer->code==='WALK-IN'?'retail':($customer->customerType?->price_tier==='wholesale'?'wholesale':'retail') }}" data-walk-in="{{ $customer->code==='WALK-IN'?1:0 }}" @selected(old('customer_id',request('customer_id',$saleMode==='cash'?$walkIn?->id:null))==$customer->id)>{{ $customer->code==='WALK-IN'?'Walk-in Customer (Cash / Retail)':$customer->name }}</option>@empty<option value="">No eligible customers—create one first</option>@endforelse</select>
@if($saleMode==='credit' && $customers->isEmpty())<div class="alert alert-danger py-2">No credit-enabled customers exist. Create a customer before continuing.</div>@endif
<label class="form-label">Pricing channel</label><div class="channel-choice mb-3"><div><input type="radio" name="channel" id="channel-retail" value="retail" @checked(old('channel','retail')==='retail')><label for="channel-retail"><i class="bi bi-person me-1"></i> RETAIL</label></div><div><input type="radio" name="channel" id="channel-wholesale" value="wholesale" @checked(old('channel')==='wholesale')><label for="channel-wholesale"><i class="bi bi-boxes me-1"></i> WHOLESALE</label></div></div>
@if($saleMode==='credit')<label class="form-label">Payment due date</label><input class="form-control mb-3" type="date" name="due_date" value="{{ old('due_date',now()->addDays(30)->toDateString()) }}" min="{{ now()->toDateString() }}" required><input type="hidden" name="payment_method" value="">@endif
<hr><div class="d-flex justify-content-between"><span>Subtotal</span><strong id="subtotal">Rs. 0.00</strong></div><label class="form-label mt-3">Discount</label><input class="form-control" name="discount_amount" id="discount" type="number" value="{{ old('discount_amount',0) }}" min="0" step=".01"><div class="d-flex justify-content-between align-items-end mt-3"><span>Grand total</span><span class="pos-total" id="grand">Rs. 0.00</span></div>
@if($saleMode==='cash')<hr><label class="form-label">Payment method</label><select class="form-select mb-3" name="payment_method" id="method">@foreach(['cash'=>'Cash','credit_card'=>'Credit Card','debit_card'=>'Debit Card','qr'=>'QR Payment','cheque'=>'Cheque','bank_transfer'=>'Bank Transfer','mobile_wallet'=>'Mobile Wallet','online_payment'=>'Online Payment'] as $value=>$label)<option value="{{ $value }}" @selected(old('payment_method')===$value)>{{ $label }}</option>@endforeach</select><div id="cheque" class="d-none"><input class="form-control mb-2" name="cheque_number" value="{{ old('cheque_number') }}" placeholder="Cheque number"><input class="form-control mb-2" name="cheque_bank" value="{{ old('cheque_bank') }}" placeholder="Bank"><input class="form-control mb-3" type="date" name="cheque_date" value="{{ old('cheque_date') }}"></div><input class="form-control mb-3" name="payment_reference" value="{{ old('payment_reference') }}" placeholder="Payment reference (optional)">@else<div class="alert alert-info py-2 mt-3 mb-3"><i class="bi bi-info-circle me-1"></i>No payment method is needed now.</div>@endif
<button class="btn {{ $saleMode==='credit'?'btn-primary':'btn-success' }} btn-lg w-100" id="post" @disabled($saleMode==='credit'&&$customers->isEmpty())>{{ $saleMode==='credit'?'Post Credit Invoice':'Complete Cash Sale' }}</button>
</div></div></aside></div></form>
@push('scripts')<script>
let rowIndex=0;const cart=new Map(),picker=document.querySelector('#product-picker'),cartBody=document.querySelector('#cart'),saleMode=@json($saleMode);const selectedChannel=()=>document.querySelector('input[name="channel"]:checked').value;const money=value=>'Rs. '+Number(value).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});
function totals(){let subtotal=0;cartBody.querySelectorAll('tr[data-id]').forEach(row=>{const line=Number(row.querySelector('.qty').value)*Number(row.querySelector('.price').value);subtotal+=line;row.querySelector('.line').textContent=money(line)});const grand=Math.max(0,subtotal-Number(document.querySelector('#discount').value||0));document.querySelector('#subtotal').textContent=money(subtotal);document.querySelector('#grand').textContent=money(grand);document.querySelector('#paid').value=saleMode==='cash'?grand.toFixed(2):'0'}
function updateChannel(){const channel=selectedChannel();cart.forEach(row=>row.querySelector('.price').value=channel==='retail'?row.dataset.retail:row.dataset.wholesale);totals()}
function addProduct(option){if(cart.has(option.value)){const qty=cart.get(option.value).querySelector('.qty');qty.value=Number(qty.value)+1;totals();return}document.querySelector('#empty')?.remove();const row=document.createElement('tr');row.dataset.id=option.value;row.dataset.retail=option.dataset.retail;row.dataset.wholesale=option.dataset.wholesale;row.innerHTML=`<td class="ps-3"><strong>${option.dataset.name}</strong><div class="small text-muted">${option.dataset.code} · Available ${option.dataset.stock}</div><input type="hidden" name="items[${rowIndex}][product_id]" value="${option.value}"></td><td><input class="form-control qty" name="items[${rowIndex}][quantity]" type="number" min=".0001" max="${option.dataset.stock}" step=".0001" value="1"></td><td><input class="form-control price" name="items[${rowIndex}][unit_price]" type="number" min="0" step=".01" value="${selectedChannel()==='retail'?option.dataset.retail:option.dataset.wholesale}"></td><td class="line"></td><td><button class="btn btn-light remove" type="button">×</button></td>`;row.querySelectorAll('input').forEach(input=>input.oninput=totals);row.querySelector('.remove').onclick=()=>{cart.delete(option.value);row.remove();totals()};cartBody.append(row);cart.set(option.value,row);rowIndex++;totals()}
picker.onchange=()=>{if(picker.value)addProduct(picker.selectedOptions[0]);picker.value=''};document.querySelectorAll('input[name="channel"]').forEach(input=>input.onchange=updateChannel);document.querySelector('#customer').onchange=event=>{const option=event.target.selectedOptions[0];if(!option)return;const walkIn=option.dataset.walkIn==='1';if(walkIn){document.querySelector('#channel-retail').checked=true;document.querySelector('#channel-wholesale').disabled=true}else document.querySelector('#channel-wholesale').disabled=false;const desired=option.dataset.channel;document.querySelector('#channel-'+desired).checked=true;updateChannel()};document.querySelector('#discount').oninput=totals;document.querySelector('#method')?.addEventListener('change',event=>document.querySelector('#cheque').classList.toggle('d-none',event.target.value!=='cheque'));document.querySelector('#customer').dispatchEvent(new Event('change'));totals();
</script>@endpush
@endsection
