@extends('layouts.app')
@section('title',$sale->document_number)
@push('styles')
<style>
.invoice-sheet{max-width:900px;margin:auto;background:#fff;border:1px solid #dce3ec;border-top:7px solid #123566;box-shadow:0 12px 35px rgba(15,31,56,.1);color:#172033}.invoice-pad{padding:30px 38px}.invoice-logo{width:215px;height:56px;object-fit:contain;object-position:left}.invoice-label{font-size:.68rem;text-transform:uppercase;letter-spacing:.1em;color:#68758a;font-weight:700}.invoice-title{color:#fff;letter-spacing:.08em}.invoice-header{border-bottom:2px solid #dbe4ef}.invoice-meta{min-width:285px;background:linear-gradient(135deg,#123566,#1e4f91);color:#fff;border-radius:12px;padding:18px 20px;box-shadow:0 7px 16px rgba(18,53,102,.18)}.invoice-meta .invoice-label{color:#bcd4f5}.invoice-party{background:#f7f9fc;border:1px solid #e3e9f1;border-radius:10px;padding:16px 18px}.invoice-table{border:1px solid #e0e7ef}.invoice-table thead th{background:#123566!important;color:#fff!important}.invoice-table td,.invoice-table th{padding:9px 10px}.invoice-table tbody tr:nth-child(even){background:#f8fafc}.invoice-total{background:linear-gradient(145deg,#f1f6fc,#e8f0fa);border:1px solid #d7e3f1;border-radius:10px;padding:15px 17px}.invoice-total .grand{border-top:2px solid #123566;border-bottom:2px solid #123566;padding:8px 0;margin:7px 0;color:#123566}.invoice-instructions{background:#f7f9fc;border:1px solid #e1e8f0;border-left:4px solid #2563eb;border-radius:7px;padding:11px 15px;font-size:.78rem}.invoice-signatures{display:grid;grid-template-columns:repeat(3,1fr);gap:38px;margin-top:38px;text-align:center;font-size:.72rem}.invoice-signature{border-top:1px solid #667085;padding-top:6px}.invoice-footer{border-top:1px solid #dce3ec;margin-top:20px;padding-top:9px;text-align:center;font-size:.68rem;color:#68758a}
@page{size:A4 portrait;margin:10mm}
@media print{html,body{margin:0!important;padding:0!important;background:#fff!important;-webkit-print-color-adjust:exact;print-color-adjust:exact}.sidebar,.topbar,.no-print,.alert{display:none!important}.main{margin:0!important;min-height:0!important}.content{padding:0!important}.invoice-sheet{position:relative;width:190mm!important;max-width:190mm!important;height:276mm!important;max-height:276mm!important;margin:0!important;border:0!important;border-top:2mm solid #123566!important;box-shadow:none!important;overflow:hidden!important}.invoice-pad{position:relative;height:273mm!important;padding:5mm 4mm 10mm!important}.invoice-logo{width:50mm;height:13mm}.invoice-header{padding-bottom:3mm!important;margin-bottom:3mm!important}.invoice-meta{min-width:65mm;padding:3mm 4mm!important;border-radius:2mm}.invoice-meta h2{font-size:13pt!important}.invoice-meta .fs-5{font-size:11pt!important}.invoice-party{padding:3mm!important;margin-bottom:3mm!important}.invoice-table{font-size:7.5pt;margin-bottom:2mm!important}.invoice-table thead{display:table-header-group}.invoice-table tr{break-inside:avoid}.invoice-table td,.invoice-table th{padding:1.5mm!important}.invoice-total{padding:2.5mm 3mm!important}.invoice-total .fs-5{font-size:11pt!important}.invoice-instructions{padding:2mm 3mm!important;margin-top:3mm!important;font-size:6.8pt!important}.invoice-instructions li{margin-bottom:.4mm}.invoice-signatures{position:absolute;left:4mm;right:4mm;bottom:12mm;margin:0!important;gap:10mm;font-size:6.5pt}.invoice-footer{position:absolute;left:4mm;right:4mm;bottom:3mm;margin:0!important;padding-top:2mm!important;font-size:6pt}.invoice-signatures,.invoice-instructions,.invoice-total,.invoice-footer{break-inside:avoid}}
</style>
@endpush
@section('content')
<div class="d-flex justify-content-between mb-4 no-print"><div><a href="{{ route('sales.index') }}" class="text-decoration-none"><i class="bi bi-arrow-left"></i> Sales invoices</a><h1 class="h3 mt-2">{{ $sale->document_number }} @if($sale->status==='voided')<span class="badge text-bg-danger">VOIDED</span>@endif</h1></div><div class="d-flex gap-2">@if($sale->status==='posted')<a class="btn btn-outline-primary" href="{{ route('sales-exchanges.create',$sale) }}"><i class="bi bi-arrow-left-right"></i> Exchange</a><a class="btn btn-outline-danger" href="{{ route('sale-returns.create',$sale) }}">Return</a>@endif<button class="btn btn-primary" onclick="window.print()"><i class="bi bi-printer"></i> Print Customer Invoice</button></div></div>
@if($sale->status==='voided')<div class="alert alert-danger"><strong>This invoice was voided.</strong> {{ $sale->reversal_reason }}</div>@elseif((float)$sale->paid_amount===0.0)<form class="card card-body mb-4 no-print" method="POST" action="{{ route('sales.void',$sale) }}">@csrf<div class="d-flex gap-2"><input class="form-control" name="reason" minlength="5" required placeholder="Reason for voiding this unpaid invoice"><button class="btn btn-danger text-nowrap" onclick="return confirm('Void this invoice and reverse its stock and accounting entries?')">Void invoice</button></div></form>@endif

<article class="invoice-sheet"><div class="invoice-pad">
<header class="invoice-header d-flex justify-content-between align-items-start pb-3 mb-4"><div><img class="invoice-logo" src="{{ asset('images/supun-group-logo.svg') }}" alt="{{ $company->name ?? 'Supun Group' }}"><div class="small mt-2"><strong>{{ $company->legal_name ?: ($company->name ?? 'Supun Group') }}</strong><br>@if($company->address) {!! nl2br(e($company->address)) !!}<br>@endif @if($company->phone)Tel: {{ $company->phone }} @endif @if($company->email) · {{ $company->email }} @endif<br>@if($company->registration_number)Company Reg: {{ $company->registration_number }} @endif @if($company->tax_number) · Tax No: {{ $company->tax_number }} @endif</div></div><div class="text-end invoice-meta"><h2 class="h4 fw-bold invoice-title">{{ strtoupper($sale->channel) }} SALES INVOICE</h2><div class="fs-5 fw-bold">{{ $sale->document_number }}</div><div class="mt-2"><span class="invoice-label">Invoice date</span><br>{{ $sale->sale_date->format('d F Y, h:i A') }}</div>@if($sale->due_date)<div class="mt-2"><span class="invoice-label">Payment due date</span><br><strong>{{ $sale->due_date->format('d F Y') }}</strong></div>@endif</div></header>

<section class="invoice-party row g-3 mb-4"><div class="col-7"><div class="invoice-label mb-1">Bill to</div>@if($sale->customer->is_walk_in||$sale->customer->code==='WALK-IN')<div class="fw-bold fs-6">{{ $sale->walk_in_customer_name ?: 'Cash Customer' }}</div><div>Temporary walk-in sale - no customer account created</div>@else<div class="fw-bold fs-6">{{ $sale->customer->business_name ?: $sale->customer->name }}</div>@if($sale->customer->business_name)<div>Attn: {{ $sale->customer->name }}</div>@endif<div>Customer code: {{ $sale->customer->code }}</div>@if($sale->customer->billing_address)<div>{!! nl2br(e($sale->customer->billing_address)) !!}</div>@endif @if($sale->customer->phone)<div>Tel: {{ $sale->customer->phone }}</div>@endif @if($sale->customer->email)<div>Email: {{ $sale->customer->email }}</div>@endif @endif</div><div class="col-5 text-end"><div class="invoice-label mb-1">Sale details</div><div><strong>Channel:</strong> {{ Str::headline($sale->channel) }}</div><div><strong>Terms:</strong> {{ $sale->payment_type==='credit'?'Credit'.($sale->due_date?' · Due '.$sale->due_date->format('d M Y'):''):'Paid at sale' }}</div><div><strong>Status:</strong> {{ Str::headline($sale->payment_status) }}</div><div><strong>Salesperson:</strong> {{ $sale->user->name }}</div><div><strong>Currency:</strong> LKR</div></div></section>

<table class="table invoice-table align-middle"><thead><tr><th style="width:6%">#</th><th>Item code / Description</th><th class="text-end">Qty</th><th class="text-end">Unit price</th><th class="text-end">Discount</th><th class="text-end">Amount (LKR)</th></tr></thead><tbody>@foreach($sale->items as $item)<tr><td>{{ $loop->iteration }}</td><td><strong>{{ $item->product->item_code }}</strong> · {{ $item->product->name }}@if($item->product->warranty_months)<br><small class="text-muted">Warranty: {{ $item->product->warranty_months }} months, subject to warranty terms</small>@endif</td><td class="text-end">{{ rtrim(rtrim(number_format($item->quantity,4,'.',''),'0'),'.') }}</td><td class="text-end">{{ number_format($item->unit_price,2) }}</td><td class="text-end">{{ number_format($item->discount_amount,2) }}</td><td class="text-end fw-semibold">{{ number_format($item->line_total,2) }}</td></tr>@endforeach</tbody></table>

<div class="row g-4 mt-1"><div class="col-7"><div class="invoice-label mb-2">Payment record</div>@forelse($sale->payments as $payment)<div class="small border-bottom py-1 d-flex justify-content-between"><span>{{ $payment->payment_date->format('d M Y') }} · {{ Str::headline($payment->payment_method) }} @if($payment->reference)({{ $payment->reference }})@endif<br><span class="text-muted">Receipt {{ $payment->receipt_number }}</span></span><strong>Rs. {{ number_format($payment->amount,2) }}</strong></div>@empty<div class="small text-muted">No payment recorded against this invoice.</div>@endforelse @if($sale->notes)<div class="mt-3"><div class="invoice-label">Invoice notes</div><div class="small">{{ $sale->notes }}</div></div>@endif</div><div class="col-5"><div class="invoice-total"><div class="d-flex justify-content-between"><span>Subtotal</span><strong>{{ number_format($sale->subtotal,2) }}</strong></div><div class="d-flex justify-content-between"><span>Discount</span><span>({{ number_format($sale->discount_amount,2) }})</span></div>@if((float)$sale->tax_amount>0)<div class="d-flex justify-content-between"><span>Tax</span><span>{{ number_format($sale->tax_amount,2) }}</span></div>@endif<div class="d-flex justify-content-between grand fs-5 fw-bold"><span>Total</span><span>Rs. {{ number_format($sale->grand_total,2) }}</span></div><div class="d-flex justify-content-between"><span>Paid / credit applied</span><span>{{ number_format($sale->paid_amount,2) }}</span></div><div class="d-flex justify-content-between mt-2 fs-5 fw-bold {{ (float)$sale->balance_amount>0?'text-danger':'text-success' }}"><span>Balance due</span><span>Rs. {{ number_format($sale->balance_amount,2) }}</span></div></div></div></div>

<section class="invoice-instructions mt-4"><strong>Customer information and instructions</strong><ul class="mb-0 mt-1 ps-3"><li>Please quote invoice number <strong>{{ $sale->document_number }}</strong> with every payment or inquiry.</li>@if((float)$sale->balance_amount>0)<li>Outstanding amount of <strong>Rs. {{ number_format($sale->balance_amount,2) }}</strong> must be settled {{ $sale->due_date?'on or before '.$sale->due_date->format('d F Y'):'according to the agreed credit terms' }}.</li>@endif<li>Check quantities, model/item codes, physical condition and accessories at delivery.</li><li>Keep this original invoice for warranty, exchange or return requests. Warranty is subject to manufacturer and company terms.</li><li>Report invoice discrepancies promptly and contact {{ $company->phone ?: ($company->email ?: 'our customer service team') }} before returning goods.</li></ul></section>

<section class="invoice-signatures"><div class="invoice-signature">Prepared by<br><strong>{{ $sale->user->name }}</strong></div><div class="invoice-signature">Authorized by<br>Name / Signature</div><div class="invoice-signature">Received by customer<br>Name / Signature / Date</div></section>
<footer class="invoice-footer">Thank you for your business · This is a computer-generated sales invoice from {{ $company->name ?? 'Supun Group' }}.</footer>
</div></article>
@if(request('print'))@push('scripts')<script>window.addEventListener('load',()=>window.print())</script>@endpush @endif
@endsection
