@extends('layouts.app')
@section('title',($record->exists?'Edit ':'Add ').$title)
@section('content')
@php($backUrl=$returnTo ?: route($route.'.index'))
<div class="mb-4"><a href="{{ $backUrl }}" class="text-decoration-none"><i class="bi bi-arrow-left"></i> {{ $returnTo?'Back to POS':'Back' }}</a><h1 class="h3 page-title mt-2">{{ $record->exists?'Edit':'Add' }} {{ $title }}</h1>@if($returnTo)<p class="text-muted">Create the customer, then you will return to the sale with this customer selected.</p>@endif</div>
<form method="POST" action="{{ $record->exists?route($route.'.update',$record):route($route.'.store') }}">@csrf @if($record->exists)@method('PUT')@endif @if($returnTo)<input type="hidden" name="return_to" value="{{ $returnTo }}">@endif
<div class="card"><div class="card-body p-4"><h2 class="h6 fw-bold mb-3">Basic information</h2><div class="row g-3">
<div class="col-md-3"><label class="form-label">Code</label><input class="form-control" name="code" value="{{ old('code',$record->code) }}" required></div>
<div class="col-md-5"><label class="form-label">Name</label><input class="form-control" name="name" value="{{ old('name',$record->name) }}" required></div>
<div class="col-md-4"><label class="form-label">{{ $route==='customers'?'Business name':'Contact person' }}</label><input class="form-control" name="{{ $route==='customers'?'business_name':'contact_person' }}" value="{{ old($route==='customers'?'business_name':'contact_person',$route==='customers'?$record->business_name:$record->contact_person) }}"></div>
<div class="col-md-4"><label class="form-label">Phone</label><input class="form-control" name="phone" value="{{ old('phone',$record->phone) }}"></div><div class="col-md-4"><label class="form-label">Email</label><input class="form-control" type="email" name="email" value="{{ old('email',$record->email) }}"></div><div class="col-12"><label class="form-label">Address</label><textarea class="form-control" name="address" rows="2">{{ old('address',$route==='customers'?$record->billing_address:$record->address) }}</textarea></div></div>
@if($route==='customers')<hr class="my-4"><h2 class="h6 fw-bold mb-3">Credit settings</h2><div class="row g-3"><div class="col-md-4"><label class="form-label">Customer type</label><select class="form-select" name="customer_type"><option value="RET">Retail</option><option value="WHO">Wholesale</option></select></div><div class="col-md-4"><label class="form-label">Default due term</label><select class="form-select" name="default_due_term">@foreach(['7_days'=>'7 days','14_days'=>'14 days','30_days'=>'30 days','end_of_month'=>'End of month','custom'=>'Custom'] as $value=>$label)<option value="{{ $value }}" @selected(old('default_due_term',$record->default_due_term)===$value)>{{ $label }}</option>@endforeach</select></div><div class="col-md-4 d-flex align-items-end"><div class="form-check form-switch mb-2"><input type="hidden" name="credit_enabled" value="0"><input class="form-check-input" type="checkbox" name="credit_enabled" value="1" @checked(old('credit_enabled',$returnTo?true:$record->credit_enabled))><label>Credit enabled</label></div></div></div>@endif
<hr class="my-4"><div class="form-check form-switch mb-4"><input type="hidden" name="is_active" value="0"><input class="form-check-input" type="checkbox" name="is_active" value="1" @checked(old('is_active',$record->exists?$record->is_active:true))><label>Active</label></div><button class="btn btn-primary px-4">Save {{ $title }}</button><a class="btn btn-light ms-2" href="{{ $backUrl }}">Cancel</a></div></div></form>
@endsection
