@extends('layouts.app')
@section('title', $account ? 'Edit Account' : 'New Account')
@section('content')
<div class="d-flex justify-content-between align-items-start mb-4"><div><h1 class="h3 page-title mb-1">{{ $account ? 'Edit Account' : 'Create Account' }}</h1><p class="text-muted mb-0">Maintain the chart of accounts used by journals and financial reports.</p></div><a href="{{ route('accounting.accounts') }}" class="btn btn-outline-secondary">Back to Chart of Accounts</a></div>
<form method="post" action="{{ $account ? route('accounting.accounts.update', $account) : route('accounting.accounts.store') }}" class="card">@csrf @if($account) @method('PUT') @endif
<div class="card-body p-4">@if($errors->any())<div class="alert alert-danger"><strong>Please correct the highlighted fields.</strong><ul class="mb-0 mt-2">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="row g-3"><div class="col-md-3"><label class="form-label">Account code</label><input name="code" class="form-control @error('code') is-invalid @enderror" value="{{ old('code',$account?->code) }}" maxlength="30" required></div><div class="col-md-9"><label class="form-label">Account name</label><input name="name" class="form-control @error('name') is-invalid @enderror" value="{{ old('name',$account?->name) }}" maxlength="150" required></div>
<div class="col-md-6"><label class="form-label">Account type</label><select name="account_type_id" id="account-type" class="form-select" required><option value="">Select type</option>@foreach($types as $type)<option value="{{ $type->id }}" @selected(old('account_type_id',$account?->account_type_id)==$type->id)>{{ $type->name }}</option>@endforeach</select></div><div class="col-md-6"><label class="form-label">Parent account</label><select name="parent_id" id="parent-account" class="form-select"><option value="">No parent (top-level)</option>@foreach($parentAccounts as $parent)<option value="{{ $parent->id }}" data-type="{{ $parent->account_type_id }}" @selected(old('parent_id',$account?->parent_id)==$parent->id)>{{ $parent->code }} — {{ $parent->name }}</option>@endforeach</select><div class="form-text">Only parents matching the selected account type can be used.</div></div>
<div class="col-12"><label class="form-label">Description</label><textarea name="description" class="form-control" rows="3" maxlength="1000">{{ old('description',$account?->description) }}</textarea></div>
@foreach([['is_control_account','Control account','Transactions are posted by system processes.'],['allow_manual_posting','Allow manual posting','Users may select this account in manual journals.'],['is_active','Active','Available for new transactions and reports.']] as [$field,$label,$help])<div class="col-md-4"><input type="hidden" name="{{ $field }}" value="0"><div class="form-check form-switch border rounded-3 p-3 ps-5 h-100"><input class="form-check-input" type="checkbox" name="{{ $field }}" value="1" id="{{ $field }}" @checked(old($field,$account ? $account->{$field} : ($field !== 'is_control_account')))><label class="form-check-label fw-semibold" for="{{ $field }}">{{ $label }}</label><div class="small text-muted">{{ $help }}</div></div></div>@endforeach</div></div>
<div class="card-footer bg-white d-flex justify-content-end gap-2 p-3"><a href="{{ route('accounting.accounts') }}" class="btn btn-light">Cancel</a><button class="btn btn-primary">{{ $account ? 'Save Changes' : 'Create Account' }}</button></div></form>
<script>document.addEventListener('DOMContentLoaded',function(){const type=document.getElementById('account-type'),parent=document.getElementById('parent-account');function filterParents(){Array.from(parent.options).forEach(function(option,index){if(index)return option.hidden=!!type.value&&option.dataset.type!==type.value;});if(parent.selectedOptions[0]?.hidden)parent.value='';}type.addEventListener('change',filterParents);filterParents();document.getElementById('is_control_account').addEventListener('change',function(){if(this.checked)document.getElementById('allow_manual_posting').checked=false;});});</script>
@endsection
