@extends('layouts.app')
@section('title','Chart of Accounts')
@section('content')
<div class="d-flex justify-content-between align-items-start mb-4"><div><h1 class="h3 page-title mb-1">Chart of Accounts</h1><p class="text-muted mb-0">Complete account structure and balances from posted journals.</p></div><div class="d-flex gap-2"><a href="{{ route('accounting.trial-balance') }}" class="btn btn-outline-primary">Trial Balance</a><a href="{{ route('accounting.journals') }}" class="btn btn-primary">Accounting Journals</a></div></div>
<div class="card"><div class="card-body border-bottom"><form class="row g-2"><div class="col-md-5"><input class="form-control" name="search" value="{{ request('search') }}" placeholder="Search account code or name"></div><div class="col-md-4"><select class="form-select" name="type"><option value="">All account types</option>@foreach($types as $type)<option value="{{ $type->id }}" @selected(request('type')==$type->id)>{{ $type->name }}</option>@endforeach</select></div><div class="col"><button class="btn btn-outline-secondary">Filter</button></div></form></div>
<div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th class="ps-4">Code</th><th>Account</th><th>Type</th><th>Parent</th><th>Posting</th><th>Status</th><th class="text-end">Current balance</th><th class="text-end pe-4">Action</th></tr></thead><tbody>
@forelse($accounts as $account) @php($total=$balances->get($account->id)) @php($movement=(float)($total?->debit_total??0)-(float)($total?->credit_total??0)) @php($balance=(float)$account->opening_balance+($account->type->normal_balance==='credit' ? -$movement : $movement))
<tr><td class="ps-4 fw-semibold">{{ $account->code }}</td><td><div class="fw-semibold">{{ $account->name }}</div>@if($account->description)<small class="text-muted">{{ $account->description }}</small>@endif</td><td>{{ $account->type->name }}</td><td>{{ $account->parent?->code ? $account->parent->code.' — '.$account->parent->name : '—' }}</td><td>@if($account->is_control_account)<span class="badge text-bg-info">Control</span>@elseif($account->allow_manual_posting)<span class="badge text-bg-light">Manual allowed</span>@else<span class="badge text-bg-secondary">System only</span>@endif</td><td><span class="badge {{ $account->is_active?'text-bg-success':'text-bg-secondary' }}">{{ $account->is_active?'Active':'Inactive' }}</span></td><td class="text-end fw-semibold">Rs. {{ number_format($balance,2) }}</td><td class="text-end pe-4"><a class="btn btn-sm btn-light" href="{{ route('accounting.ledger',$account) }}">Ledger</a></td></tr>
@empty<tr><td colspan="8" class="text-center text-muted py-5">No accounts found.</td></tr>@endforelse</tbody></table></div><div class="p-3">{{ $accounts->links() }}</div></div>
@endsection
